/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ActionSheet: typeof import('./src/components/ActionSheet.vue')['default']
    ApiKeys: typeof import('./src/components/ApiKeys.vue')['default']
    AppCard: typeof import('./src/components/dashboard/AppCard.vue')['default']
    AppStat: typeof import('./src/components/package/AppStat.vue')['default']
    AppTable: typeof import('./src/components/tables/AppTable.vue')['default']
    Banner: typeof import('./src/components/Banner.vue')['default']
    BlurBg: typeof import('./src/components/BlurBg.vue')['default']
    BundleTable: typeof import('./src/components/tables/BundleTable.vue')['default']
    ChannelCard: typeof import('./src/components/package/ChannelCard.vue')['default']
    ChannelTable: typeof import('./src/components/tables/ChannelTable.vue')['default']
    Dashboard: typeof import('./src/components/dashboard/Dashboard.vue')['default']
    DeviceCard: typeof import('./src/components/package/DeviceCard.vue')['default']
    DeviceTable: typeof import('./src/components/tables/DeviceTable.vue')['default']
    Dialog: typeof import('./src/components/Dialog.vue')['default']
    DropdownOrganization: typeof import('./src/components/dashboard/DropdownOrganization.vue')['default']
    DropdownProfile: typeof import('./src/components/dashboard/DropdownProfile.vue')['default']
    IIonCopyOutline: typeof import('~icons/ion/copy-outline')['default']
    InfoRow: typeof import('./src/components/package/InfoRow.vue')['default']
    LineChartStats: typeof import('./src/components/LineChartStats.vue')['default']
    Loading: typeof import('./src/components/Loading.vue')['default']
    LogTable: typeof import('./src/components/tables/LogTable.vue')['default']
    MobileStats: typeof import('./src/components/MobileStats.vue')['default']
    Navbar: typeof import('./src/components/Navbar.vue')['default']
    NewUserModal: typeof import('./src/components/NewUserModal.vue')['default']
    OrganizationPicker: typeof import('./src/components/dashboard/OrganizationPicker.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Searchbar: typeof import('./src/components/Searchbar.vue')['default']
    SharedApps: typeof import('./src/components/dashboard/SharedApps.vue')['default']
    SharedUserTable: typeof import('./src/components/tables/SharedUserTable.vue')['default']
    Sidebar: typeof import('./src/components/Sidebar.vue')['default']
    Spinner: typeof import('./src/components/Spinner.vue')['default']
    StatsBar: typeof import('./src/components/StatsBar.vue')['default']
    Steps: typeof import('./src/components/dashboard/Steps.vue')['default']
    Table: typeof import('./src/components/Table.vue')['default']
    Tabs: typeof import('./src/components/Tabs.vue')['default']
    TabSidebar: typeof import('./src/components/TabSidebar.vue')['default']
    TitleHead: typeof import('./src/components/TitleHead.vue')['default']
    Toast: typeof import('./src/components/Toast.vue')['default']
    Toggle: typeof import('./src/components/Toggle.vue')['default']
    TopApps: typeof import('./src/components/dashboard/TopApps.vue')['default']
    Usage: typeof import('./src/components/dashboard/Usage.vue')['default']
    UsageCard: typeof import('./src/components/dashboard/UsageCard.vue')['default']
    VersionCard: typeof import('./src/components/package/VersionCard.vue')['default']
    WelcomeBanner: typeof import('./src/components/dashboard/WelcomeBanner.vue')['default']
  }
}
