// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AccountPanel: typeof import('./src/components/settings/AccountPanel.vue')['default']
    ActionSheet: typeof import('./src/components/ActionSheet.vue')['default']
    AppCard: typeof import('./src/components/dashboard/AppCard.vue')['default']
    Banner: typeof import('./src/components/Banner.vue')['default']
    copy: typeof import('./src/components/Sidebar copy.vue')['default']
    Dialog: typeof import('./src/components/Dialog.vue')['default']
    DropdownProfile: typeof import('./src/components/dashboard/DropdownProfile.vue')['default']
    IIonAddOutline: typeof import('~icons/ion/add-outline')['default']
    IIonArrowBack: typeof import('~icons/ion/arrow-back')['default']
    IIonBookOutline: typeof import('~icons/ion/book-outline')['default']
    IIonChevronBackOutline: typeof import('~icons/ion/chevron-back-outline')['default']
    IIonChevronForwardOutline: typeof import('~icons/ion/chevron-forward-outline')['default']
    IIonCopyOutline: typeof import('~icons/ion/copy-outline')['default']
    IIonKeyOutline: typeof import('~icons/ion/key-outline')['default']
    IIonLogoDiscord: typeof import('~icons/ion/logo-discord')['default']
    LineChartStats: typeof import('./src/components/LineChartStats.vue')['default']
    Loading: typeof import('./src/components/Loading.vue')['default']
    MobileStats: typeof import('./src/components/MobileStats.vue')['default']
    Navbar: typeof import('./src/components/Navbar.vue')['default']
    NewUserModal: typeof import('./src/components/NewUserModal.vue')['default']
    NotificationsPanel: typeof import('./src/components/settings/NotificationsPanel.vue')['default']
    PlansPanel: typeof import('./src/components/settings/PlansPanel.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Searchbar: typeof import('./src/components/Searchbar.vue')['default']
    SettingsSidebar: typeof import('./src/components/settings/SettingsSidebar.vue')['default']
    SharedApps: typeof import('./src/components/dashboard/SharedApps.vue')['default']
    Sidebar: typeof import('./src/components/Sidebar.vue')['default']
    Spinner: typeof import('./src/components/Spinner.vue')['default']
    TitleHead: typeof import('./src/components/TitleHead.vue')['default']
    Toast: typeof import('./src/components/Toast.vue')['default']
    TopApps: typeof import('./src/components/dashboard/TopApps.vue')['default']
    Usage: typeof import('./src/components/dashboard/Usage.vue')['default']
    UsageCard: typeof import('./src/components/dashboard/UsageCard.vue')['default']
    WelcomeBanner: typeof import('./src/components/dashboard/WelcomeBanner.vue')['default']
  }
  export interface ComponentCustomProperties {
    vInfiniteScroll: typeof import('element-plus/es')['ElInfiniteScroll']
  }
}
