// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AccountPanel: typeof import('./src/components/settings/AccountPanel.vue')['default']
    ActionSheet: typeof import('./src/components/ActionSheet.vue')['default']
    AppCard: typeof import('./src/components/dashboard/AppCard.vue')['default']
    AppStat: typeof import('./src/components/package/AppStat.vue')['default']
    AppTable: typeof import('./src/components/tables/AppTable.vue')['default']
    Banner: typeof import('./src/components/Banner.vue')['default']
    BundleTable: typeof import('./src/components/tables/BundleTable.vue')['default']
    ChannelCard: typeof import('./src/components/package/ChannelCard.vue')['default']
    Channels: typeof import('./src/components/package/Channels.vue')['default']
    ChannelTable: typeof import('./src/components/tables/ChannelTable.vue')['default']
    copy: typeof import('./src/components/tables/DeviceTable copy.vue')['default']
    Dashboard: typeof import('./src/components/dashboard/Dashboard.vue')['default']
    DeviceCard: typeof import('./src/components/package/DeviceCard.vue')['default']
    Devices: typeof import('./src/components/package/Devices.vue')['default']
    DeviceTable: typeof import('./src/components/tables/DeviceTable.vue')['default']
    Dialog: typeof import('./src/components/Dialog.vue')['default']
    DropdownProfile: typeof import('./src/components/dashboard/DropdownProfile.vue')['default']
    IIonBookOutline: typeof import('~icons/ion/book-outline')['default']
    IIonCameraOutline: typeof import('~icons/ion/camera-outline')['default']
    IIonChevronForwardOutline: typeof import('~icons/ion/chevron-forward-outline')['default']
    IIonCopyOutline: typeof import('~icons/ion/copy-outline')['default']
    IIonKeyOutline: typeof import('~icons/ion/key-outline')['default']
    IIonLogoDiscord: typeof import('~icons/ion/logo-discord')['default']
    InfoRow: typeof import('./src/components/package/InfoRow.vue')['default']
    LineChartStats: typeof import('./src/components/LineChartStats.vue')['default']
    Loading: typeof import('./src/components/Loading.vue')['default']
    LogTable: typeof import('./src/components/tables/LogTable.vue')['default']
    MobileStats: typeof import('./src/components/MobileStats.vue')['default']
    Navbar: typeof import('./src/components/Navbar.vue')['default']
    NewUserModal: typeof import('./src/components/NewUserModal.vue')['default']
    NotificationsPanel: typeof import('./src/components/settings/NotificationsPanel.vue')['default']
    PlansPanel: typeof import('./src/components/settings/PlansPanel.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Searchbar: typeof import('./src/components/Searchbar.vue')['default']
    SettingsSidebar: typeof import('./src/components/settings/SettingsSidebar.vue')['default']
    SharedApps: typeof import('./src/components/dashboard/SharedApps.vue')['default']
    SharedUserTable: typeof import('./src/components/tables/SharedUserTable.vue')['default']
    Sidebar: typeof import('./src/components/Sidebar.vue')['default']
    Spinner: typeof import('./src/components/Spinner.vue')['default']
    Steps: typeof import('./src/components/dashboard/Steps.vue')['default']
    Table: typeof import('./src/components/Table.vue')['default']
    Tabs: typeof import('./src/components/Tabs.vue')['default']
    TitleHead: typeof import('./src/components/TitleHead.vue')['default']
    Toast: typeof import('./src/components/Toast.vue')['default']
    TopApps: typeof import('./src/components/dashboard/TopApps.vue')['default']
    Usage: typeof import('./src/components/dashboard/Usage.vue')['default']
    UsageCard: typeof import('./src/components/dashboard/UsageCard.vue')['default']
    VersionCard: typeof import('./src/components/package/VersionCard.vue')['default']
    Versions: typeof import('./src/components/package/Versions.vue')['default']
    WelcomeBanner: typeof import('./src/components/dashboard/WelcomeBanner.vue')['default']
  }
  export interface ComponentCustomProperties {
    vInfiniteScroll: typeof import('element-plus/es')['ElInfiniteScroll']
  }
}
