export const statsActionFilters = [
  ['action-ping', 'ping'],
  ['action-delete', 'delete'],
  ['action-reset', 'reset'],
  ['action-set', 'set'],
  ['action-get', 'get'],
  ['action-set-fail', 'set_fail'],
  ['action-update-fail', 'update_fail'],
  ['action-download-fail', 'download_fail'],
  ['action-windows-path-fail', 'windows_path_fail'],
  ['action-canonical-path-fail', 'canonical_path_fail'],
  ['action-directory-path-fail', 'directory_path_fail'],
  ['action-unzip-fail', 'unzip_fail'],
  ['action-low-mem-fail', 'low_mem_fail'],
  ['action-download-0', 'download_0'],
  ['action-download-10', 'download_10'],
  ['action-download-20', 'download_20'],
  ['action-download-30', 'download_30'],
  ['action-download-40', 'download_40'],
  ['action-download-50', 'download_50'],
  ['action-download-60', 'download_60'],
  ['action-download-70', 'download_70'],
  ['action-download-80', 'download_80'],
  ['action-download-90', 'download_90'],
  ['action-download-complete', 'download_complete'],
  ['action-download-manifest-start', 'download_manifest_start'],
  ['action-download-manifest-complete', 'download_manifest_complete'],
  ['action-download-zip-start', 'download_zip_start'],
  ['action-download-zip-complete', 'download_zip_complete'],
  ['action-download-manifest-file-fail', 'download_manifest_file_fail'],
  ['action-download-manifest-checksum-fail', 'download_manifest_checksum_fail'],
  ['action-download-manifest-brotli-fail', 'download_manifest_brotli_fail'],
  ['action-decrypt-fail', 'decrypt_fail'],
  ['action-app-moved-to-foreground', 'app_moved_to_foreground'],
  ['action-app-moved-to-background', 'app_moved_to_background'],
  ['action-app-crash', 'app_crash'],
  ['action-app-crash-native', 'app_crash_native'],
  ['action-app-anr', 'app_anr'],
  ['action-app-killed-low-memory', 'app_killed_low_memory'],
  ['action-app-killed-excessive-resource-usage', 'app_killed_excessive_resource_usage'],
  ['action-app-initialization-failure', 'app_initialization_failure'],
  ['action-app-memory-warning', 'app_memory_warning'],
  ['action-webview-javascript-error', 'webview_javascript_error'],
  ['action-webview-unhandled-rejection', 'webview_unhandled_rejection'],
  ['action-webview-resource-error', 'webview_resource_error'],
  ['action-webview-security-policy-violation', 'webview_security_policy_violation'],
  ['action-webview-unclean-restart', 'webview_unclean_restart'],
  ['action-webview-render-process-gone', 'webview_render_process_gone'],
  ['action-webview-content-process-terminated', 'webview_content_process_terminated'],
  ['action-os-version-changed', 'os_version_changed'],
  ['action-native-app-version-changed', 'native_app_version_changed'],
  ['action-uninstall', 'uninstall'],
  ['action-need-plan-upgrade', 'needPlanUpgrade'],
  ['action-missing-bundle', 'missingBundle'],
  ['action-no-new', 'noNew'],
  ['action-disable-platform-ios', 'disablePlatformIos'],
  ['action-disable-platform-android', 'disablePlatformAndroid'],
  ['action-disable-platform-electron', 'disablePlatformElectron'],
  ['action-disable-auto-update-to-major', 'disableAutoUpdateToMajor'],
  ['action-cannot-update-via-private-channel', 'cannotUpdateViaPrivateChannel'],
  ['action-disable-auto-update-to-minor', 'disableAutoUpdateToMinor'],
  ['action-disable-auto-update-to-patch', 'disableAutoUpdateToPatch'],
  ['action-channel-misconfigured', 'channelMisconfigured'],
  ['action-disable-auto-update-metadata', 'disableAutoUpdateMetadata'],
  ['action-disable-auto-update-under-native', 'disableAutoUpdateUnderNative'],
  ['action-disable-dev-build', 'disableDevBuild'],
  ['action-disable-prod-build', 'disableProdBuild'],
  ['action-disable-emulator', 'disableEmulator'],
  ['action-disable-device', 'disableDevice'],
  ['action-cannot-get-bundle', 'cannotGetBundle'],
  ['action-checksum-fail', 'checksum_fail'],
  ['action-key-mismatch', 'keyMismatch'],
  ['action-no-channel-or-override', 'NoChannelOrOverride'],
  ['action-set-channel', 'setChannel'],
  ['action-get-channel', 'getChannel'],
  ['action-rate-limited', 'rateLimited'],
  ['action-disable-auto-update', 'disableAutoUpdate'],
  ['action-invalid-ip', 'InvalidIp'],
  ['action-blocked-by-server-url', 'blocked_by_server_url'],
  ['action-backend-refusal', 'backend_refusal'],
  ['action-custom-id-blocked', 'customIdBlocked'],
] as const

export const filterToAction: Record<string, string> = Object.fromEntries(statsActionFilters)
export const actionToFilter: Record<string, string> = Object.fromEntries(
  statsActionFilters.map(([filterKey, actionValue]) => [actionValue, filterKey]),
)

export function createActionFilterState(): Record<string, boolean> {
  return Object.fromEntries(statsActionFilters.map(([filterKey]) => [filterKey, false]))
}
