--
-- PostgreSQL database dump
--

\restrict YsYZEaO3BszkE6LdZGbQtoK6rTI2vSwskiAAtdvLaVd19vUlmb87YLnjI7ykEy2

-- Dumped from database version 17.6
-- Dumped by pg_dump version 17.7 (Homebrew)


--
-- Name: disable_update; Type: TYPE; Schema: public; Owner: -
--

CREATE TYPE public.disable_update AS ENUM (
    'major',
    'minor',
    'patch',
    'version_number',
    'none'
);


--
-- Name: manifest_entry; Type: TYPE; Schema: public; Owner: -
--

CREATE TYPE public.manifest_entry AS (
	file_name character varying,
	s3_path character varying,
	file_hash character varying
);


--
-- Name: stripe_status; Type: TYPE; Schema: public; Owner: -
--

CREATE TYPE public.stripe_status AS ENUM (
    'created',
    'succeeded',
    'updated',
    'failed',
    'deleted',
    'canceled'
);


--
-- Name: user_min_right; Type: TYPE; Schema: public; Owner: -
--

CREATE TYPE public.user_min_right AS ENUM (
    'invite_read',
    'invite_upload',
    'invite_write',
    'invite_admin',
    'invite_super_admin',
    'read',
    'upload',
    'write',
    'admin',
    'super_admin'
);


--
-- Name: one_month_ahead(); Type: FUNCTION; Schema: public; Owner: -
--

CREATE FUNCTION public.one_month_ahead() RETURNS timestamp without time zone
    LANGUAGE plpgsql
    SET search_path TO ''
    AS $$
BEGIN
   RETURN NOW() + INTERVAL '1 month';
END;
$$;


--
-- PostgreSQL database dump complete
--

\unrestrict YsYZEaO3BszkE6LdZGbQtoK6rTI2vSwskiAAtdvLaVd19vUlmb87YLnjI7ykEy2

--
-- PostgreSQL database dump
--

\restrict pbCT0yc029IeBjc8FCsV1lorh1n1SPb373suxARvFyTDkbau37xN9hJfxUUtsO2

-- Dumped from database version 17.6
-- Dumped by pg_dump version 17.7 (Homebrew)




--
-- Name: app_versions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.app_versions (
    id bigint NOT NULL,
    created_at timestamp with time zone DEFAULT now(),
    app_id character varying NOT NULL,
    name character varying NOT NULL,
    updated_at timestamp with time zone DEFAULT now(),
    deleted boolean DEFAULT false NOT NULL,
    external_url character varying,
    checksum character varying,
    session_key character varying,
    storage_provider text DEFAULT 'r2'::text NOT NULL,
    min_update_version character varying,
    native_packages jsonb[],
    owner_org uuid NOT NULL,
    user_id uuid,
    r2_path character varying,
    manifest public.manifest_entry[],
    link text,
    comment text,
    manifest_count integer DEFAULT 0 NOT NULL,
    key_id character varying(20),
    cli_version character varying
);

ALTER TABLE ONLY public.app_versions REPLICA IDENTITY FULL;


--
-- Name: app_versions_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.app_versions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.app_versions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: apps; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.apps (
    created_at timestamp with time zone DEFAULT now(),
    app_id character varying NOT NULL,
    icon_url character varying NOT NULL,
    user_id uuid,
    name character varying,
    last_version character varying,
    updated_at timestamp with time zone,
    id uuid DEFAULT gen_random_uuid(),
    retention bigint DEFAULT '2592000'::bigint NOT NULL,
    owner_org uuid NOT NULL,
    default_upload_channel character varying DEFAULT 'production'::character varying NOT NULL,
    transfer_history jsonb[] DEFAULT '{}'::jsonb[],
    channel_device_count bigint DEFAULT 0 NOT NULL,
    manifest_bundle_count bigint DEFAULT 0 NOT NULL,
    expose_metadata boolean DEFAULT false NOT NULL
);

ALTER TABLE ONLY public.apps REPLICA IDENTITY FULL;


--
-- Name: channel_devices; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.channel_devices (
    created_at timestamp with time zone DEFAULT now(),
    channel_id bigint NOT NULL,
    app_id character varying NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    device_id text NOT NULL,
    id bigint NOT NULL,
    owner_org uuid NOT NULL
);

ALTER TABLE ONLY public.channel_devices REPLICA IDENTITY FULL;


--
-- Name: channel_devices_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.channel_devices ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.channel_devices_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: channels; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.channels (
    id bigint NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    name character varying NOT NULL,
    app_id character varying NOT NULL,
    version bigint NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    public boolean DEFAULT false NOT NULL,
    disable_auto_update_under_native boolean DEFAULT true NOT NULL,
    ios boolean DEFAULT true NOT NULL,
    android boolean DEFAULT true NOT NULL,
    allow_device_self_set boolean DEFAULT false NOT NULL,
    allow_emulator boolean DEFAULT true NOT NULL,
    allow_dev boolean DEFAULT true NOT NULL,
    disable_auto_update public.disable_update DEFAULT 'major'::public.disable_update NOT NULL,
    owner_org uuid NOT NULL,
    created_by uuid NOT NULL,
    allow_device boolean DEFAULT true NOT NULL,
    allow_prod boolean DEFAULT true NOT NULL
);

ALTER TABLE ONLY public.channels REPLICA IDENTITY FULL;


--
-- Name: channel_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.channels ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.channel_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: manifest; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.manifest (
    id integer NOT NULL,
    app_version_id bigint NOT NULL,
    file_name character varying NOT NULL,
    s3_path character varying NOT NULL,
    file_hash character varying NOT NULL,
    file_size bigint DEFAULT 0
)
WITH (autovacuum_vacuum_scale_factor='0.05', autovacuum_analyze_scale_factor='0.02');

ALTER TABLE ONLY public.manifest REPLICA IDENTITY FULL;


--
-- Name: manifest_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.manifest_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: manifest_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.manifest_id_seq OWNED BY public.manifest.id;


--
-- Name: org_users; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.org_users (
    id bigint NOT NULL,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now(),
    user_id uuid NOT NULL,
    org_id uuid NOT NULL,
    app_id character varying,
    channel_id bigint,
    user_right public.user_min_right
);


--
-- Name: org_users_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.org_users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.org_users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: orgs; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.orgs (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    created_by uuid NOT NULL,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now(),
    logo text,
    name text NOT NULL,
    management_email text NOT NULL,
    customer_id character varying,
    stats_updated_at timestamp without time zone,
    last_stats_updated_at timestamp without time zone,
    enforcing_2fa boolean DEFAULT false NOT NULL,
    email_preferences jsonb DEFAULT '{"onboarding": true, "usage_limit": true, "credit_usage": true, "device_error": true, "weekly_stats": true, "monthly_stats": true, "bundle_created": true, "bundle_deployed": true, "deploy_stats_24h": true, "billing_period_stats": true, "channel_self_rejected": true}'::jsonb NOT NULL,
    password_policy_config jsonb,
    enforce_hashed_api_keys boolean DEFAULT false NOT NULL,
    require_apikey_expiration boolean DEFAULT false NOT NULL,
    max_apikey_expiration_days integer
);

ALTER TABLE ONLY public.orgs REPLICA IDENTITY FULL;


--
-- Name: stripe_info; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.stripe_info (
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    subscription_id character varying,
    customer_id character varying NOT NULL,
    status public.stripe_status,
    product_id character varying NOT NULL,
    trial_at timestamp with time zone DEFAULT now() NOT NULL,
    price_id character varying,
    is_good_plan boolean DEFAULT true,
    plan_usage bigint DEFAULT '0'::bigint,
    subscription_metered json DEFAULT '{}'::json NOT NULL,
    subscription_anchor_start timestamp with time zone DEFAULT now() NOT NULL,
    subscription_anchor_end timestamp with time zone DEFAULT public.one_month_ahead() NOT NULL,
    canceled_at timestamp with time zone,
    mau_exceeded boolean DEFAULT false,
    storage_exceeded boolean DEFAULT false,
    bandwidth_exceeded boolean DEFAULT false,
    id integer NOT NULL,
    plan_calculated_at timestamp with time zone,
    build_time_exceeded boolean DEFAULT false
);

ALTER TABLE ONLY public.stripe_info REPLICA IDENTITY FULL;


--
-- Name: stripe_info_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.stripe_info_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: stripe_info_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.stripe_info_id_seq OWNED BY public.stripe_info.id;


--
-- Name: manifest id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.manifest ALTER COLUMN id SET DEFAULT nextval('public.manifest_id_seq'::regclass);


--
-- Name: stripe_info id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.stripe_info ALTER COLUMN id SET DEFAULT nextval('public.stripe_info_id_seq'::regclass);


--
-- Name: app_versions app_versions_name_app_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.app_versions
    ADD CONSTRAINT app_versions_name_app_id_key UNIQUE (name, app_id);


--
-- Name: app_versions app_versions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.app_versions
    ADD CONSTRAINT app_versions_pkey PRIMARY KEY (id);


--
-- Name: apps apps_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.apps
    ADD CONSTRAINT apps_pkey PRIMARY KEY (app_id);


--
-- Name: channel_devices channel_devices_app_id_device_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.channel_devices
    ADD CONSTRAINT channel_devices_app_id_device_id_key UNIQUE (app_id, device_id);


--
-- Name: channel_devices channel_devices_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.channel_devices
    ADD CONSTRAINT channel_devices_pkey PRIMARY KEY (id);


--
-- Name: channels channel_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.channels
    ADD CONSTRAINT channel_pkey PRIMARY KEY (id);


--
-- Name: manifest manifest_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.manifest
    ADD CONSTRAINT manifest_pkey PRIMARY KEY (id);


--
-- Name: org_users org_users_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.org_users
    ADD CONSTRAINT org_users_pkey PRIMARY KEY (id);


--
-- Name: orgs orgs_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.orgs
    ADD CONSTRAINT orgs_pkey PRIMARY KEY (id);


--
-- Name: stripe_info stripe_info_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.stripe_info
    ADD CONSTRAINT stripe_info_pkey PRIMARY KEY (customer_id);


--
-- Name: orgs unique customer_id on orgs; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.orgs
    ADD CONSTRAINT "unique customer_id on orgs" UNIQUE (customer_id);


--
-- Name: channel_devices unique_device_app; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.channel_devices
    ADD CONSTRAINT unique_device_app UNIQUE (device_id, app_id);


--
-- Name: channels unique_name_app_id; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.channels
    ADD CONSTRAINT unique_name_app_id UNIQUE (name, app_id);


--
-- Name: orgs unique_name_created_by; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.orgs
    ADD CONSTRAINT unique_name_created_by UNIQUE (name, created_by);


--
-- Name: finx_app_versions_owner_org; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX finx_app_versions_owner_org ON public.app_versions USING btree (owner_org);


--
-- Name: finx_apps_owner_org; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX finx_apps_owner_org ON public.apps USING btree (owner_org);


--
-- Name: finx_apps_user_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX finx_apps_user_id ON public.apps USING btree (user_id);


--
-- Name: finx_channel_devices_channel_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX finx_channel_devices_channel_id ON public.channel_devices USING btree (channel_id);


--
-- Name: finx_channel_devices_owner_org; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX finx_channel_devices_owner_org ON public.channel_devices USING btree (owner_org);


--
-- Name: finx_channels_app_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX finx_channels_app_id ON public.channels USING btree (app_id);


--
-- Name: finx_channels_owner_org; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX finx_channels_owner_org ON public.channels USING btree (owner_org);


--
-- Name: finx_channels_version; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX finx_channels_version ON public.channels USING btree (version);


--
-- Name: finx_org_users_channel_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX finx_org_users_channel_id ON public.org_users USING btree (channel_id);


--
-- Name: finx_org_users_org_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX finx_org_users_org_id ON public.org_users USING btree (org_id);


--
-- Name: finx_org_users_user_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX finx_org_users_user_id ON public.org_users USING btree (user_id);


--
-- Name: finx_orgs_created_by; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX finx_orgs_created_by ON public.orgs USING btree (created_by);


--
-- Name: finx_orgs_stripe_info; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX finx_orgs_stripe_info ON public.stripe_info USING btree (product_id);


--
-- Name: idx_app_id_app_versions; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_app_id_app_versions ON public.app_versions USING btree (app_id);


--
-- Name: idx_app_id_name_app_versions; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_app_id_name_app_versions ON public.app_versions USING btree (app_id, name);


--
-- Name: idx_app_versions_created_at; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_app_versions_created_at ON public.app_versions USING btree (created_at);


--
-- Name: idx_app_versions_created_at_app_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_app_versions_created_at_app_id ON public.app_versions USING btree (created_at, app_id);


--
-- Name: idx_app_versions_deleted; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_app_versions_deleted ON public.app_versions USING btree (deleted);


--
-- Name: idx_app_versions_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_app_versions_id ON public.app_versions USING btree (id);


--
-- Name: idx_app_versions_name; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_app_versions_name ON public.app_versions USING btree (name);


--
-- Name: idx_app_versions_owner_org_not_deleted; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_app_versions_owner_org_not_deleted ON public.app_versions USING btree (owner_org) WHERE (deleted = false);


--
-- Name: idx_app_versions_retention_cleanup; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_app_versions_retention_cleanup ON public.app_versions USING btree (deleted, created_at, app_id) WHERE (deleted = false);


--
-- Name: idx_channels_app_id_name; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_channels_app_id_name ON public.channels USING btree (app_id, name);


--
-- Name: idx_channels_app_id_version; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_channels_app_id_version ON public.channels USING btree (app_id, version);


--
-- Name: idx_channels_public_app_id_android; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_channels_public_app_id_android ON public.channels USING btree (public, app_id, android);


--
-- Name: idx_channels_public_app_id_ios; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_channels_public_app_id_ios ON public.channels USING btree (public, app_id, ios);


--
-- Name: idx_manifest_app_version_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_manifest_app_version_id ON public.manifest USING btree (app_version_id);


--
-- Name: idx_manifest_file_name_hash_version; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_manifest_file_name_hash_version ON public.manifest USING btree (file_name, file_hash, app_version_id);


--
-- Name: idx_orgs_customer_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_orgs_customer_id ON public.orgs USING btree (customer_id);


--
-- Name: idx_orgs_email_preferences; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_orgs_email_preferences ON public.orgs USING gin (email_preferences);


--
-- Name: idx_stripe_info_customer_covering; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_stripe_info_customer_covering ON public.stripe_info USING btree (customer_id) INCLUDE (product_id, subscription_anchor_start, subscription_anchor_end);


--
-- Name: idx_stripe_info_trial; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_stripe_info_trial ON public.stripe_info USING btree (trial_at) WHERE (trial_at IS NOT NULL);


--
-- Name: org_users_app_id_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX org_users_app_id_idx ON public.org_users USING btree (app_id);


--
-- Name: si_customer_cover_uidx; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX si_customer_cover_uidx ON public.stripe_info USING btree (customer_id) INCLUDE (status, trial_at, mau_exceeded, storage_exceeded, bandwidth_exceeded);


--
-- Name: si_customer_status_trial_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX si_customer_status_trial_idx ON public.stripe_info USING btree (customer_id, status, trial_at) INCLUDE (mau_exceeded, storage_exceeded, bandwidth_exceeded);


--
-- PostgreSQL database dump complete
--

\unrestrict pbCT0yc029IeBjc8FCsV1lorh1n1SPb373suxARvFyTDkbau37xN9hJfxUUtsO2

