// swift-tools-version: 5.9
import PackageDescription

// DO NOT MODIFY THIS FILE - managed by Capacitor CLI commands
let package = Package(
    name: "CapApp-SPM",
    platforms: [.iOS(.v15)],
    products: [
        .library(
            name: "CapApp-SPM",
            targets: ["CapApp-SPM"])
    ],
    dependencies: [
        .package(url: "https://github.com/ionic-team/capacitor-swift-pm.git", exact: "8.3.4"),
        .package(name: "CapacitorActionSheet", path: "../../../node_modules/@capacitor/action-sheet"),
        .package(name: "CapacitorApp", path: "../../../node_modules/@capacitor/app"),
        .package(name: "CapacitorAppLauncher", path: "../../../node_modules/@capacitor/app-launcher"),
        .package(name: "CapacitorBrowser", path: "../../../node_modules/@capacitor/browser"),
        .package(name: "CapacitorCamera", path: "../../../node_modules/@capacitor/camera"),
        .package(name: "CapacitorClipboard", path: "../../../node_modules/@capacitor/clipboard"),
        .package(name: "CapacitorDevice", path: "../../../node_modules/@capacitor/device"),
        .package(name: "CapacitorDialog", path: "../../../node_modules/@capacitor/dialog"),
        .package(name: "CapacitorFilesystem", path: "../../../node_modules/@capacitor/filesystem"),
        .package(name: "CapacitorGeolocation", path: "../../../node_modules/@capacitor/geolocation"),
        .package(name: "CapacitorHaptics", path: "../../../node_modules/@capacitor/haptics"),
        .package(name: "CapacitorKeyboard", path: "../../../node_modules/@capacitor/keyboard"),
        .package(name: "CapacitorLocalNotifications", path: "../../../node_modules/@capacitor/local-notifications"),
        .package(name: "CapacitorNetwork", path: "../../../node_modules/@capacitor/network"),
        .package(name: "CapacitorPreferences", path: "../../../node_modules/@capacitor/preferences"),
        .package(name: "CapacitorPushNotifications", path: "../../../node_modules/@capacitor/push-notifications"),
        .package(name: "CapacitorScreenReader", path: "../../../node_modules/@capacitor/screen-reader"),
        .package(name: "CapacitorShare", path: "../../../node_modules/@capacitor/share"),
        .package(name: "CapacitorSplashScreen", path: "../../../node_modules/@capacitor/splash-screen"),
        .package(name: "CapacitorStatusBar", path: "../../../node_modules/@capacitor/status-bar"),
        .package(name: "CapacitorTextZoom", path: "../../../node_modules/@capacitor/text-zoom"),
        .package(name: "CapacitorToast", path: "../../../node_modules/@capacitor/toast"),
        .package(name: "CapgoCameraPreview", path: "../../../node_modules/@capgo/camera-preview"),
        .package(name: "CapgoCapacitorAccelerometer", path: "../../../node_modules/@capgo/capacitor-accelerometer"),
        .package(name: "CapgoCapacitorAndroidAgeSignals", path: "../../../node_modules/@capgo/capacitor-android-age-signals"),
        .package(name: "CapgoCapacitorAndroidInlineInstall", path: "../../../node_modules/@capgo/capacitor-android-inline-install"),
        .package(name: "CapgoCapacitorAndroidKiosk", path: "../../../node_modules/@capgo/capacitor-android-kiosk"),
        .package(name: "CapgoCapacitorAndroidSmsRetriever", path: "../../../node_modules/@capgo/capacitor-android-sms-retriever"),
        .package(name: "CapgoCapacitorAndroidUsagestatsmanager", path: "../../../node_modules/@capgo/capacitor-android-usagestatsmanager"),
        .package(name: "CapgoCapacitorAppinsights", path: "../../../node_modules/@capgo/capacitor-appinsights"),
        .package(name: "CapgoCapacitorAppsflyer", path: "../../../node_modules/@capgo/capacitor-appsflyer"),
        .package(name: "CapgoCapacitorAudioRecorder", path: "../../../node_modules/@capgo/capacitor-audio-recorder"),
        .package(name: "CapgoCapacitorAudioSession", path: "../../../node_modules/@capgo/capacitor-audio-session"),
        .package(name: "CapgoCapacitorAutofillSavePassword", path: "../../../node_modules/@capgo/capacitor-autofill-save-password"),
        .package(name: "CapgoCapacitorBarometer", path: "../../../node_modules/@capgo/capacitor-barometer"),
        .package(name: "CapgoCapacitorBrightness", path: "../../../node_modules/@capgo/capacitor-brightness"),
        .package(name: "CapgoCapacitorCompass", path: "../../../node_modules/@capgo/capacitor-compass"),
        .package(name: "CapgoCapacitorCrisp", path: "../../../node_modules/@capgo/capacitor-crisp"),
        .package(name: "CapgoCapacitorDataStorageSqlite", path: "../../../node_modules/@capgo/capacitor-data-storage-sqlite"),
        .package(name: "CapgoCapacitorDocumentScanner", path: "../../../node_modules/@capgo/capacitor-document-scanner"),
        .package(name: "CapgoCapacitorDownloader", path: "../../../node_modules/@capgo/capacitor-downloader"),
        .package(name: "CapgoCapacitorFile", path: "../../../node_modules/@capgo/capacitor-file"),
        .package(name: "CapgoCapacitorFileCompressor", path: "../../../node_modules/@capgo/capacitor-file-compressor"),
        .package(name: "CapgoCapacitorFilePicker", path: "../../../node_modules/@capgo/capacitor-file-picker"),
        .package(name: "CapgoCapacitorFileSharer", path: "../../../node_modules/@capgo/capacitor-file-sharer"),
        .package(name: "CapgoCapacitorFlash", path: "../../../node_modules/@capgo/capacitor-flash"),
        .package(name: "CapgoCapacitorHomeIndicator", path: "../../../node_modules/@capgo/capacitor-home-indicator"),
        .package(name: "CapgoCapacitorInAppReview", path: "../../../node_modules/@capgo/capacitor-in-app-review"),
        .package(name: "CapgoCapacitorInstallReferrer", path: "../../../node_modules/@capgo/capacitor-install-referrer"),
        .package(name: "CapgoCapacitorIntentLauncher", path: "../../../node_modules/@capgo/capacitor-intent-launcher"),
        .package(name: "CapgoCapacitorIntercom", path: "../../../node_modules/@capgo/capacitor-intercom"),
        .package(name: "CapgoCapacitorIsRoot", path: "../../../node_modules/@capgo/capacitor-is-root"),
        .package(name: "CapgoCapacitorIvsPlayer", path: "../../../node_modules/@capgo/capacitor-ivs-player"),
        .package(name: "CapgoCapacitorJwPlayer", path: "../../../node_modules/@capgo/capacitor-jw-player"),
        .package(name: "CapgoCapacitorKeepAwake", path: "../../../node_modules/@capgo/capacitor-keep-awake"),
        .package(name: "CapgoCapacitorLaunchNavigator", path: "../../../node_modules/@capgo/capacitor-launch-navigator"),
        .package(name: "CapgoCapacitorLightSensor", path: "../../../node_modules/@capgo/capacitor-light-sensor"),
        .package(name: "CapgoCapacitorLlm", path: "../../../node_modules/@capgo/capacitor-llm"),
        .package(name: "CapgoCapacitorMediaSession", path: "../../../node_modules/@capgo/capacitor-media-session"),
        .package(name: "CapgoCapacitorMqtt", path: "../../../node_modules/@capgo/capacitor-mqtt"),
        .package(name: "CapgoCapacitorMute", path: "../../../node_modules/@capgo/capacitor-mute"),
        .package(name: "CapgoCapacitorMuxPlayer", path: "../../../node_modules/@capgo/capacitor-mux-player"),
        .package(name: "CapgoCapacitorNativeNavigation", path: "../../../node_modules/@capgo/capacitor-native-navigation"),
        .package(name: "CapgoCapacitorNavigationBar", path: "../../../node_modules/@capgo/capacitor-navigation-bar"),
        .package(name: "CapgoCapacitorPdfGenerator", path: "../../../node_modules/@capgo/capacitor-pdf-generator"),
        .package(name: "CapgoCapacitorPersistentAccount", path: "../../../node_modules/@capgo/capacitor-persistent-account"),
        .package(name: "CapgoCapacitorPhotoLibrary", path: "../../../node_modules/@capgo/capacitor-photo-library"),
        .package(name: "CapgoCapacitorPrinter", path: "../../../node_modules/@capgo/capacitor-printer"),
        .package(name: "CapgoCapacitorPrivacyScreen", path: "../../../node_modules/@capgo/capacitor-privacy-screen"),
        .package(name: "CapgoCapacitorProximity", path: "../../../node_modules/@capgo/capacitor-proximity"),
        .package(name: "CapgoCapacitorRecaptcha", path: "../../../node_modules/@capgo/capacitor-recaptcha"),
        .package(name: "CapgoCapacitorRudderstack", path: "../../../node_modules/@capgo/capacitor-rudderstack"),
        .package(name: "CapgoCapacitorScreenOrientation", path: "../../../node_modules/@capgo/capacitor-screen-orientation"),
        .package(name: "CapgoCapacitorScreenRecorder", path: "../../../node_modules/@capgo/capacitor-screen-recorder"),
        .package(name: "CapgoCapacitorShake", path: "../../../node_modules/@capgo/capacitor-shake"),
        .package(name: "CapgoCapacitorSim", path: "../../../node_modules/@capgo/capacitor-sim"),
        .package(name: "CapgoCapacitorSpeechSynthesis", path: "../../../node_modules/@capgo/capacitor-speech-synthesis"),
        .package(name: "CapgoCapacitorTextinteraction", path: "../../../node_modules/@capgo/capacitor-textinteraction"),
        .package(name: "CapgoCapacitorUpdater", path: "../../../node_modules/@capgo/capacitor-updater"),
        .package(name: "CapgoCapacitorUploader", path: "../../../node_modules/@capgo/capacitor-uploader"),
        .package(name: "CapgoCapacitorVideoPlayer", path: "../../../node_modules/@capgo/capacitor-video-player"),
        .package(name: "CapgoCapacitorVideoThumbnails", path: "../../../node_modules/@capgo/capacitor-video-thumbnails"),
        .package(name: "CapgoCapacitorVolumeButtons", path: "../../../node_modules/@capgo/capacitor-volume-buttons"),
        .package(name: "CapgoCapacitorWebviewCrash", path: "../../../node_modules/@capgo/capacitor-webview-crash"),
        .package(name: "CapgoCapacitorWebviewGuardian", path: "../../../node_modules/@capgo/capacitor-webview-guardian"),
        .package(name: "CapgoCapacitorWifi", path: "../../../node_modules/@capgo/capacitor-wifi"),
        .package(name: "CapgoCapacitorYoutubePlayer", path: "../../../node_modules/@capgo/capacitor-youtube-player"),
        .package(name: "CapgoCapacitorZebraDatawedge", path: "../../../node_modules/@capgo/capacitor-zebra-datawedge"),
        .package(name: "CapgoCapacitorZip", path: "../../../node_modules/@capgo/capacitor-zip"),
        .package(name: "CapgoInappbrowser", path: "../../../node_modules/@capgo/inappbrowser"),
        .package(name: "CapgoNativeAudio", path: "../../../node_modules/@capgo/native-audio"),
        .package(name: "CapgoNativeMarket", path: "../../../node_modules/@capgo/native-market"),
        .package(name: "CapgoNativegeocoder", path: "../../../node_modules/@capgo/nativegeocoder"),
        .package(name: "CapgoRicoh360", path: "../../../node_modules/@capgo/ricoh360"),
        .package(name: "RevenuecatPurchasesCapacitor", path: "../../../node_modules/@revenuecat/purchases-capacitor")
    ],
    targets: [
        .target(
            name: "CapApp-SPM",
            dependencies: [
                .product(name: "Capacitor", package: "capacitor-swift-pm"),
                .product(name: "Cordova", package: "capacitor-swift-pm"),
                .product(name: "CapacitorActionSheet", package: "CapacitorActionSheet"),
                .product(name: "CapacitorApp", package: "CapacitorApp"),
                .product(name: "CapacitorAppLauncher", package: "CapacitorAppLauncher"),
                .product(name: "CapacitorBrowser", package: "CapacitorBrowser"),
                .product(name: "CapacitorCamera", package: "CapacitorCamera"),
                .product(name: "CapacitorClipboard", package: "CapacitorClipboard"),
                .product(name: "CapacitorDevice", package: "CapacitorDevice"),
                .product(name: "CapacitorDialog", package: "CapacitorDialog"),
                .product(name: "CapacitorFilesystem", package: "CapacitorFilesystem"),
                .product(name: "CapacitorGeolocation", package: "CapacitorGeolocation"),
                .product(name: "CapacitorHaptics", package: "CapacitorHaptics"),
                .product(name: "CapacitorKeyboard", package: "CapacitorKeyboard"),
                .product(name: "CapacitorLocalNotifications", package: "CapacitorLocalNotifications"),
                .product(name: "CapacitorNetwork", package: "CapacitorNetwork"),
                .product(name: "CapacitorPreferences", package: "CapacitorPreferences"),
                .product(name: "CapacitorPushNotifications", package: "CapacitorPushNotifications"),
                .product(name: "CapacitorScreenReader", package: "CapacitorScreenReader"),
                .product(name: "CapacitorShare", package: "CapacitorShare"),
                .product(name: "CapacitorSplashScreen", package: "CapacitorSplashScreen"),
                .product(name: "CapacitorStatusBar", package: "CapacitorStatusBar"),
                .product(name: "CapacitorTextZoom", package: "CapacitorTextZoom"),
                .product(name: "CapacitorToast", package: "CapacitorToast"),
                .product(name: "CapgoCameraPreview", package: "CapgoCameraPreview"),
                .product(name: "CapgoCapacitorAccelerometer", package: "CapgoCapacitorAccelerometer"),
                .product(name: "CapgoCapacitorAndroidAgeSignals", package: "CapgoCapacitorAndroidAgeSignals"),
                .product(name: "CapgoCapacitorAndroidInlineInstall", package: "CapgoCapacitorAndroidInlineInstall"),
                .product(name: "CapgoCapacitorAndroidKiosk", package: "CapgoCapacitorAndroidKiosk"),
                .product(name: "CapgoCapacitorAndroidSmsRetriever", package: "CapgoCapacitorAndroidSmsRetriever"),
                .product(name: "CapgoCapacitorAndroidUsagestatsmanager", package: "CapgoCapacitorAndroidUsagestatsmanager"),
                .product(name: "CapgoCapacitorAppinsights", package: "CapgoCapacitorAppinsights"),
                .product(name: "CapgoCapacitorAppsflyer", package: "CapgoCapacitorAppsflyer"),
                .product(name: "CapgoCapacitorAudioRecorder", package: "CapgoCapacitorAudioRecorder"),
                .product(name: "CapgoCapacitorAudioSession", package: "CapgoCapacitorAudioSession"),
                .product(name: "CapgoCapacitorAutofillSavePassword", package: "CapgoCapacitorAutofillSavePassword"),
                .product(name: "CapgoCapacitorBarometer", package: "CapgoCapacitorBarometer"),
                .product(name: "CapgoCapacitorBrightness", package: "CapgoCapacitorBrightness"),
                .product(name: "CapgoCapacitorCompass", package: "CapgoCapacitorCompass"),
                .product(name: "CapgoCapacitorCrisp", package: "CapgoCapacitorCrisp"),
                .product(name: "CapgoCapacitorDataStorageSqlite", package: "CapgoCapacitorDataStorageSqlite"),
                .product(name: "CapgoCapacitorDocumentScanner", package: "CapgoCapacitorDocumentScanner"),
                .product(name: "CapgoCapacitorDownloader", package: "CapgoCapacitorDownloader"),
                .product(name: "CapgoCapacitorFile", package: "CapgoCapacitorFile"),
                .product(name: "CapgoCapacitorFileCompressor", package: "CapgoCapacitorFileCompressor"),
                .product(name: "CapgoCapacitorFilePicker", package: "CapgoCapacitorFilePicker"),
                .product(name: "CapgoCapacitorFileSharer", package: "CapgoCapacitorFileSharer"),
                .product(name: "CapgoCapacitorFlash", package: "CapgoCapacitorFlash"),
                .product(name: "CapgoCapacitorHomeIndicator", package: "CapgoCapacitorHomeIndicator"),
                .product(name: "CapgoCapacitorInAppReview", package: "CapgoCapacitorInAppReview"),
                .product(name: "CapgoCapacitorInstallReferrer", package: "CapgoCapacitorInstallReferrer"),
                .product(name: "CapgoCapacitorIntentLauncher", package: "CapgoCapacitorIntentLauncher"),
                .product(name: "CapgoCapacitorIntercom", package: "CapgoCapacitorIntercom"),
                .product(name: "CapgoCapacitorIsRoot", package: "CapgoCapacitorIsRoot"),
                .product(name: "CapgoCapacitorIvsPlayer", package: "CapgoCapacitorIvsPlayer"),
                .product(name: "CapgoCapacitorJwPlayer", package: "CapgoCapacitorJwPlayer"),
                .product(name: "CapgoCapacitorKeepAwake", package: "CapgoCapacitorKeepAwake"),
                .product(name: "CapgoCapacitorLaunchNavigator", package: "CapgoCapacitorLaunchNavigator"),
                .product(name: "CapgoCapacitorLightSensor", package: "CapgoCapacitorLightSensor"),
                .product(name: "CapgoCapacitorLlm", package: "CapgoCapacitorLlm"),
                .product(name: "CapgoCapacitorMediaSession", package: "CapgoCapacitorMediaSession"),
                .product(name: "CapgoCapacitorMqtt", package: "CapgoCapacitorMqtt"),
                .product(name: "CapgoCapacitorMute", package: "CapgoCapacitorMute"),
                .product(name: "CapgoCapacitorMuxPlayer", package: "CapgoCapacitorMuxPlayer"),
                .product(name: "CapgoCapacitorNativeNavigation", package: "CapgoCapacitorNativeNavigation"),
                .product(name: "CapgoCapacitorNavigationBar", package: "CapgoCapacitorNavigationBar"),
                .product(name: "CapgoCapacitorPdfGenerator", package: "CapgoCapacitorPdfGenerator"),
                .product(name: "CapgoCapacitorPersistentAccount", package: "CapgoCapacitorPersistentAccount"),
                .product(name: "CapgoCapacitorPhotoLibrary", package: "CapgoCapacitorPhotoLibrary"),
                .product(name: "CapgoCapacitorPrinter", package: "CapgoCapacitorPrinter"),
                .product(name: "CapgoCapacitorPrivacyScreen", package: "CapgoCapacitorPrivacyScreen"),
                .product(name: "CapgoCapacitorProximity", package: "CapgoCapacitorProximity"),
                .product(name: "CapgoCapacitorRecaptcha", package: "CapgoCapacitorRecaptcha"),
                .product(name: "CapgoCapacitorRudderstack", package: "CapgoCapacitorRudderstack"),
                .product(name: "CapgoCapacitorScreenOrientation", package: "CapgoCapacitorScreenOrientation"),
                .product(name: "CapgoCapacitorScreenRecorder", package: "CapgoCapacitorScreenRecorder"),
                .product(name: "CapgoCapacitorShake", package: "CapgoCapacitorShake"),
                .product(name: "CapgoCapacitorSim", package: "CapgoCapacitorSim"),
                .product(name: "CapgoCapacitorSpeechSynthesis", package: "CapgoCapacitorSpeechSynthesis"),
                .product(name: "CapgoCapacitorTextinteraction", package: "CapgoCapacitorTextinteraction"),
                .product(name: "CapgoCapacitorUpdater", package: "CapgoCapacitorUpdater"),
                .product(name: "CapgoCapacitorUploader", package: "CapgoCapacitorUploader"),
                .product(name: "CapgoCapacitorVideoPlayer", package: "CapgoCapacitorVideoPlayer"),
                .product(name: "CapgoCapacitorVideoThumbnails", package: "CapgoCapacitorVideoThumbnails"),
                .product(name: "CapgoCapacitorVolumeButtons", package: "CapgoCapacitorVolumeButtons"),
                .product(name: "CapgoCapacitorWebviewCrash", package: "CapgoCapacitorWebviewCrash"),
                .product(name: "CapgoCapacitorWebviewGuardian", package: "CapgoCapacitorWebviewGuardian"),
                .product(name: "CapgoCapacitorWifi", package: "CapgoCapacitorWifi"),
                .product(name: "CapgoCapacitorYoutubePlayer", package: "CapgoCapacitorYoutubePlayer"),
                .product(name: "CapgoCapacitorZebraDatawedge", package: "CapgoCapacitorZebraDatawedge"),
                .product(name: "CapgoCapacitorZip", package: "CapgoCapacitorZip"),
                .product(name: "CapgoInappbrowser", package: "CapgoInappbrowser"),
                .product(name: "CapgoNativeAudio", package: "CapgoNativeAudio"),
                .product(name: "CapgoNativeMarket", package: "CapgoNativeMarket"),
                .product(name: "CapgoNativegeocoder", package: "CapgoNativegeocoder"),
                .product(name: "CapgoRicoh360", package: "CapgoRicoh360"),
                .product(name: "RevenuecatPurchasesCapacitor", package: "RevenuecatPurchasesCapacitor")
            ]
        )
    ]
)
