platform('ios')

app_version('12.159.14')
screenshots_path('./fastlane/screenshots')

skip_binary_upload(true)
skip_metadata(true)
overwrite_screenshots(true)
submit_for_review(false)
automatic_release(false)
force(true)
