#!/usr/bin/env node
import { writeFileSync, readFileSync } from 'node:fs'
import { join } from 'node:path'

// Get version from package.json
const packageJson = JSON.parse(readFileSync('package.json', 'utf8'))
const version = packageJson.version

// Update version.ts file
const versionFilePath = join('supabase', 'functions', '_backend', 'utils', 'version.ts')
const versionFileContent = `export const version = '${version}'\n
// This is automatically generated by the update-version.js script don't edit it manually\n`

writeFileSync(versionFilePath, versionFileContent)
console.log(`Updated version.ts with version ${version}`) 
