// Rules to match requests this Snippet will handle
// (http.host eq "plugin.usecapgo.com") or (http.host eq "plugin.capgo.app") or (http.host eq "updater.capgo.com.cn") or (http.host eq "updater.spencer.co") or (http.request.full_uri wildcard "*api.capgo.app/updates*") or (http.request.full_uri wildcard "*api.capgo.app/plugin/*") or (http.request.full_uri wildcard "*api.capgo.app/stats") or (http.request.full_uri wildcard "*api.capgo.app/channel_self")
export default {
  async fetch(request) {
    /**
     * A map of the URLs to redirect to
     * @param {object} countryMap
     */
    const AS = 'https://plugin.as.capgo.app'
    const EU = 'https://plugin.eu.capgo.app'
    const NA = 'https://plugin.na.capgo.app'
    const SA = 'https://plugin.sa.capgo.app'
    const OC = 'https://plugin.oc.capgo.app'
    const AF = 'https://plugin.af.capgo.app'

    const mapped = {
      AAE: 'AF',
      ABJ: 'AF',
      ABQ: 'NA',
      ACC: 'AF',
      ADB: 'EU',
      ADD: 'AF',
      ADL: 'OC',
      AKL: 'OC',
      AKX: 'AS',
      ALA: 'AS',
      ALG: 'AF',
      AMD: 'AS',
      AMM: 'AS',
      AMS: 'EU',
      ANC: 'NA',
      ARI: 'SA',
      ARN: 'EU',
      ARU: 'SA',
      ASK: 'AF',
      ASU: 'SA',
      ATH: 'EU',
      ATL: 'NA',
      AUS: 'NA',
      BAH: 'AS',
      BAQ: 'SA',
      BCN: 'EU',
      BEG: 'EU',
      BEL: 'SA',
      BEY: 'AS',
      BGI: 'NA',
      BGR: 'NA',
      BGW: 'AS',
      BHY: 'AS',
      BKK: 'AS',
      BLR: 'AS',
      BNA: 'NA',
      BNE: 'OC',
      BNU: 'SA',
      BOD: 'EU',
      BOG: 'SA',
      BOM: 'AS',
      BOS: 'NA',
      BRU: 'EU',
      BSB: 'SA',
      BSR: 'AS',
      BTS: 'EU',
      BUD: 'EU',
      BUF: 'NA',
      BWN: 'AS',
      CAI: 'AF',
      CAN: 'AS',
      CAW: 'SA',
      CBR: 'OC',
      CCP: 'SA',
      CCU: 'AS',
      CDG: 'EU',
      CEB: 'AS',
      CFC: 'SA',
      CGB: 'SA',
      CGD: 'AS',
      CGK: 'AS',
      CGO: 'AS',
      CGP: 'AS',
      CGY: 'AS',
      CHC: 'OC',
      CKG: 'AS',
      CLE: 'NA',
      CLO: 'SA',
      CLT: 'NA',
      CMB: 'AS',
      CMH: 'NA',
      CNF: 'SA',
      CNN: 'AS',
      CNX: 'AS',
      COK: 'AS',
      COR: 'SA',
      CPH: 'EU',
      CPT: 'AF',
      CRK: 'AS',
      CSX: 'AS',
      CWB: 'SA',
      CZL: 'AF',
      CZX: 'AS',
      DAC: 'AS',
      DAD: 'AS',
      DAR: 'AF',
      DEL: 'AS',
      DEN: 'NA',
      DFW: 'NA',
      DKR: 'AF',
      DLC: 'AS',
      DME: 'EU',
      DMM: 'AS',
      DOH: 'AS',
      DPS: 'AS',
      DTW: 'NA',
      DUB: 'EU',
      DUR: 'AF',
      DUS: 'EU',
      DXB: 'AS',
      EBB: 'AF',
      EBL: 'AS',
      EVN: 'AS',
      EWR: 'NA',
      EZE: 'SA',
      FCO: 'EU',
      FIH: 'AF',
      FLN: 'SA',
      FOC: 'AS',
      FOR: 'SA',
      FRA: 'EU',
      FRU: 'AS',
      FSD: 'NA',
      FUK: 'AS',
      FUO: 'AS',
      GBE: 'AF',
      GDL: 'NA',
      GEO: 'SA',
      GIG: 'SA',
      GND: 'SA',
      GOT: 'EU',
      GRU: 'SA',
      GUA: 'NA',
      GUM: 'AS',
      GVA: 'EU',
      GYD: 'AS',
      GYE: 'SA',
      GYN: 'SA',
      HAK: 'AS',
      HAM: 'EU',
      HAN: 'AS',
      HBA: 'OC',
      HEL: 'EU',
      HFA: 'AS',
      HGH: 'AS',
      HKG: 'AS',
      HNL: 'NA',
      HRE: 'AF',
      HYD: 'AS',
      HYN: 'AS',
      IAD: 'NA',
      IAH: 'NA',
      ICN: 'AS',
      IND: 'NA',
      ISB: 'AS',
      IST: 'EU',
      ISU: 'AS',
      ITJ: 'SA',
      IXC: 'AS',
      JAX: 'NA',
      JDO: 'SA',
      JED: 'AS',
      JHB: 'AS',
      JIB: 'AF',
      JNB: 'AF',
      JOG: 'AS',
      JOI: 'SA',
      JXG: 'AS',
      KBP: 'EU',
      KCH: 'AS',
      KEF: 'EU',
      KGL: 'AF',
      KHH: 'AS',
      KHI: 'AS',
      KHN: 'AS',
      KIN: 'NA',
      KIV: 'EU',
      KIX: 'AS',
      KJA: 'AS',
      KMG: 'AS',
      KNU: 'AS',
      KTM: 'AS',
      KUL: 'AS',
      KWE: 'AS',
      KWI: 'AS',
      LAD: 'AF',
      LAS: 'NA',
      LAX: 'NA',
      LCA: 'EU',
      LED: 'EU',
      LHR: 'EU',
      LIM: 'SA',
      LIS: 'EU',
      LLK: 'AS',
      LLW: 'AF',
      LOS: 'AF',
      LPB: 'SA',
      LUN: 'AF',
      LUX: 'EU',
      LYS: 'EU',
      MAA: 'AS',
      MAD: 'EU',
      MAN: 'EU',
      MAO: 'SA',
      MBA: 'AF',
      MCI: 'NA',
      MCT: 'AS',
      MDE: 'SA',
      MEL: 'OC',
      MEM: 'NA',
      MEX: 'NA',
      MFM: 'AS',
      MIA: 'NA',
      MLE: 'AS',
      MNL: 'AS',
      MPM: 'AF',
      MRS: 'EU',
      MRU: 'AF',
      MSP: 'NA',
      MSQ: 'EU',
      MUC: 'EU',
      MXP: 'EU',
      NAG: 'AS',
      NBO: 'AF',
      NJF: 'AS',
      NNG: 'AS',
      NOU: 'OC',
      NQN: 'SA',
      NQZ: 'AS',
      NRT: 'AS',
      NVT: 'SA',
      OKA: 'AS',
      OKC: 'NA',
      OMA: 'NA',
      ORD: 'NA',
      ORF: 'NA',
      ORN: 'AF',
      OSL: 'EU',
      OTP: 'EU',
      OUA: 'AF',
      PAT: 'AS',
      PBH: 'AS',
      PBM: 'SA',
      PDX: 'NA',
      PER: 'OC',
      PHL: 'NA',
      PHX: 'NA',
      PIT: 'NA',
      PKX: 'AS',
      PMO: 'EU',
      PMW: 'SA',
      PNH: 'AS',
      POA: 'SA',
      POS: 'SA',
      PPT: 'OC',
      PRG: 'EU',
      PTY: 'SA',
      QRO: 'NA',
      QWJ: 'SA',
      RAO: 'SA',
      RDU: 'NA',
      REC: 'SA',
      RIC: 'NA',
      RIX: 'EU',
      RUH: 'AS',
      RUN: 'AF',
      SAN: 'NA',
      SAP: 'SA',
      SAT: 'NA',
      SCL: 'SA',
      SDQ: 'NA',
      SEA: 'NA',
      SFO: 'NA',
      SGN: 'AS',
      SHA: 'AS',
      SIN: 'AS',
      SJC: 'NA',
      SJK: 'SA',
      SJO: 'SA',
      SJP: 'SA',
      SJU: 'NA',
      SJW: 'AS',
      SKG: 'EU',
      SKP: 'EU',
      SLC: 'NA',
      SMF: 'NA',
      SOD: 'SA',
      SOF: 'EU',
      SSA: 'SA',
      STI: 'NA',
      STL: 'NA',
      STR: 'EU',
      SUV: 'OC',
      SYD: 'OC',
      SZX: 'AS',
      TAO: 'AS',
      TBS: 'EU',
      TEN: 'AS',
      TGU: 'SA',
      TIA: 'EU',
      TLH: 'NA',
      TLL: 'EU',
      TLV: 'AS',
      TNA: 'AS',
      TNR: 'AF',
      TPA: 'NA',
      TPE: 'AS',
      TUN: 'AF',
      TXL: 'EU',
      TYN: 'AS',
      UDI: 'SA',
      UIO: 'SA',
      ULN: 'AS',
      URT: 'AS',
      VCP: 'SA',
      VIE: 'EU',
      VIX: 'SA',
      VNO: 'EU',
      VTE: 'AS',
      WAW: 'EU',
      WDH: 'AF',
      XAP: 'SA',
      XFN: 'AS',
      XIY: 'AS',
      XNH: 'AS',
      XNN: 'AS',
      YHZ: 'NA',
      YOW: 'NA',
      YUL: 'NA',
      YVR: 'NA',
      YWG: 'NA',
      YXE: 'NA',
      YYC: 'NA',
      YYZ: 'NA',
      ZAG: 'EU',
      ZDM: 'AS',
      ZRH: 'EU',
    }

    const continentMap = {
      // Replace the countinent codes and target URLs with ones that apply to your case.
      NA,
      EU,
      AS,
      OC,
      SA,
      AF,
    }

    // Use the cf object to obtain the country of the request
    // more on the cf object: https://developers.cloudflare.com/workers/runtime-apis/request#incomingrequestcfproperties
    const continent = mapped[request.cf.colo] ?? 'EU'
    const path = new URL(request.url).pathname
    // If country is not null and is defined in the country map above, redirect.
    if (continent != null && continent in continentMap) {
      const baseUrl = continentMap[continent]
      // Remove this logging statement from your final output.
      console.log(
        `Based on ${continent}-based request, your user would go to ${baseUrl}${path}.`,
      )
      return fetch(`${baseUrl}${path}`, request)

      // If request country not in map, return another page.
    }
    return fetch(request)
  },
}
