// Rules to match requests this Snippet will handle
// Expression
// (http.host eq "plugin.usecapgo.com")
// or (http.host eq "plugin.capgo.app")
// or (http.host eq "updater.capgo.com.cn")
// or (http.host eq "updater.spencer.co")
// or (http.request.full_uri wildcard "*api.capgo.app/updates*")
// or (http.request.full_uri wildcard "*api.capgo.app/plugin/*")
// or (http.request.full_uri wildcard "*api.capgo.app/stats")
// or (http.request.full_uri wildcard "*api.capgo.app/channel_self")
export default {
  async fetch(request) {
    /**
     * A map of the URLs to redirect to
     * @param {object} countryMap
     */
    const AsiaURL = 'https://plugin.as.capgo.app'
    const EuropeURL = 'https://plugin.eu.capgo.app'
    const NorthAmericaURL = 'https://plugin.na.capgo.app'
    const SouthAmericaURL = 'https://plugin.sa.capgo.app'
    const OceaniaURL = 'https://plugin.oc.capgo.app'
    const AfricaURL = 'https://plugin.af.capgo.app'

    const AsiaZone = 'AS'
    const EuropeZone = 'EU'
    const NorthAmericaZone = 'NA'
    const SouthAmericaZone = 'SA'
    const OceaniaZone = 'OC'
    const AfricaZone = 'AF'

    const mapped = {
      AAE: AfricaZone,
      ABJ: AfricaZone,
      ABQ: NorthAmericaZone,
      ACC: AfricaZone,
      ADB: EuropeZone,
      ADD: AfricaZone,
      ADL: OceaniaZone,
      AKL: OceaniaZone,
      AKX: AsiaZone,
      ALA: AsiaZone,
      ALG: AfricaZone,
      AMD: AsiaZone,
      AMM: AsiaZone,
      AMS: EuropeZone,
      ANC: NorthAmericaZone,
      ARI: SouthAmericaZone,
      ARN: EuropeZone,
      ARU: SouthAmericaZone,
      ASK: AfricaZone,
      ASU: SouthAmericaZone,
      ATH: EuropeZone,
      ATL: NorthAmericaZone,
      AUS: NorthAmericaZone,
      BAH: AsiaZone,
      BAQ: SouthAmericaZone,
      BCN: EuropeZone,
      BEG: EuropeZone,
      BEL: SouthAmericaZone,
      BEY: AsiaZone,
      BGI: NorthAmericaZone,
      BGR: NorthAmericaZone,
      BGW: AsiaZone,
      BHY: AsiaZone,
      BKK: AsiaZone,
      BLR: AsiaZone,
      BNA: NorthAmericaZone,
      BNE: OceaniaZone,
      BNU: SouthAmericaZone,
      BOD: EuropeZone,
      BOG: SouthAmericaZone,
      BOM: AsiaZone,
      BOS: NorthAmericaZone,
      BRU: EuropeZone,
      BSB: SouthAmericaZone,
      BSR: AsiaZone,
      BTS: EuropeZone,
      BUD: EuropeZone,
      BUF: NorthAmericaZone,
      BWN: AsiaZone,
      CAI: AfricaZone,
      CAN: AsiaZone,
      CAW: SouthAmericaZone,
      CBR: OceaniaZone,
      CCP: SouthAmericaZone,
      CCU: AsiaZone,
      CDG: EuropeZone,
      CEB: AsiaZone,
      CFC: SouthAmericaZone,
      CGB: SouthAmericaZone,
      CGD: AsiaZone,
      CGK: AsiaZone,
      CGO: AsiaZone,
      CGP: AsiaZone,
      CGY: AsiaZone,
      CHC: OceaniaZone,
      CKG: AsiaZone,
      CLE: NorthAmericaZone,
      CLO: SouthAmericaZone,
      CLT: NorthAmericaZone,
      CMB: AsiaZone,
      CMH: NorthAmericaZone,
      CNF: SouthAmericaZone,
      CNN: AsiaZone,
      CNX: AsiaZone,
      COK: AsiaZone,
      COR: SouthAmericaZone,
      CPH: EuropeZone,
      CPT: AfricaZone,
      CRK: AsiaZone,
      CSX: AsiaZone,
      CWB: SouthAmericaZone,
      CZL: AfricaZone,
      CZX: AsiaZone,
      DAC: AsiaZone,
      DAD: AsiaZone,
      DAR: AfricaZone,
      DEL: AsiaZone,
      DEN: NorthAmericaZone,
      DFW: NorthAmericaZone,
      DKR: AfricaZone,
      DLC: AsiaZone,
      DME: EuropeZone,
      DMM: AsiaZone,
      DOH: AsiaZone,
      DPS: AsiaZone,
      DTW: NorthAmericaZone,
      DUB: EuropeZone,
      DUR: AfricaZone,
      DUS: EuropeZone,
      DXB: AsiaZone,
      EBB: AfricaZone,
      EBL: AsiaZone,
      EVN: AsiaZone,
      EWR: NorthAmericaZone,
      EZE: SouthAmericaZone,
      FCO: EuropeZone,
      FIH: AfricaZone,
      FLN: SouthAmericaZone,
      FOC: AsiaZone,
      FOR: SouthAmericaZone,
      FRA: EuropeZone,
      FRU: AsiaZone,
      FSD: NorthAmericaZone,
      FUK: AsiaZone,
      FUO: AsiaZone,
      GBE: AfricaZone,
      GDL: NorthAmericaZone,
      GEO: SouthAmericaZone,
      GIG: SouthAmericaZone,
      GND: SouthAmericaZone,
      GOT: EuropeZone,
      GRU: SouthAmericaZone,
      GUA: NorthAmericaZone,
      GUM: AsiaZone,
      GVA: EuropeZone,
      GYD: AsiaZone,
      GYE: SouthAmericaZone,
      GYN: SouthAmericaZone,
      HAK: AsiaZone,
      HAM: EuropeZone,
      HAN: AsiaZone,
      HBA: OceaniaZone,
      HEL: EuropeZone,
      HFA: AsiaZone,
      HGH: AsiaZone,
      HKG: AsiaZone,
      HNL: NorthAmericaZone,
      HRE: AfricaZone,
      HYD: AsiaZone,
      HYN: AsiaZone,
      IAD: NorthAmericaZone,
      IAH: NorthAmericaZone,
      ICN: AsiaZone,
      IND: NorthAmericaZone,
      ISB: AsiaZone,
      IST: EuropeZone,
      ISU: AsiaZone,
      ITJ: SouthAmericaZone,
      IXC: AsiaZone,
      JAX: NorthAmericaZone,
      JDO: SouthAmericaZone,
      JED: AsiaZone,
      JHB: AsiaZone,
      JIB: AfricaZone,
      JNB: AfricaZone,
      JOG: AsiaZone,
      JOI: SouthAmericaZone,
      JXG: AsiaZone,
      KBP: EuropeZone,
      KCH: AsiaZone,
      KEF: EuropeZone,
      KGL: AfricaZone,
      KHH: AsiaZone,
      KHI: AsiaZone,
      KHN: AsiaZone,
      KIN: NorthAmericaZone,
      KIV: EuropeZone,
      KIX: AsiaZone,
      KJA: AsiaZone,
      KMG: AsiaZone,
      KNU: AsiaZone,
      KTM: AsiaZone,
      KUL: AsiaZone,
      KWE: AsiaZone,
      KWI: AsiaZone,
      LAD: AfricaZone,
      LAS: NorthAmericaZone,
      LAX: NorthAmericaZone,
      LCA: EuropeZone,
      LED: EuropeZone,
      LHR: EuropeZone,
      LIM: SouthAmericaZone,
      LIS: EuropeZone,
      LLK: AsiaZone,
      LLW: AfricaZone,
      LOS: AfricaZone,
      LPB: SouthAmericaZone,
      LUN: AfricaZone,
      LUX: EuropeZone,
      LYS: EuropeZone,
      MAA: AsiaZone,
      MAD: EuropeZone,
      MAN: EuropeZone,
      MAO: SouthAmericaZone,
      MBA: AfricaZone,
      MCI: NorthAmericaZone,
      MCT: AsiaZone,
      MDE: SouthAmericaZone,
      MEL: OceaniaZone,
      MEM: NorthAmericaZone,
      MEX: NorthAmericaZone,
      MFM: AsiaZone,
      MIA: NorthAmericaZone,
      MLE: AsiaZone,
      MNL: AsiaZone,
      MPM: AfricaZone,
      MRS: EuropeZone,
      MRU: AfricaZone,
      MSP: NorthAmericaZone,
      MSQ: EuropeZone,
      MUC: EuropeZone,
      MXP: EuropeZone,
      NAG: AsiaZone,
      NBO: AfricaZone,
      NJF: AsiaZone,
      NNG: AsiaZone,
      NOU: OceaniaZone,
      NQN: SouthAmericaZone,
      NQZ: AsiaZone,
      NRT: AsiaZone,
      NVT: SouthAmericaZone,
      OKA: AsiaZone,
      OKC: NorthAmericaZone,
      OMA: NorthAmericaZone,
      ORD: NorthAmericaZone,
      ORF: NorthAmericaZone,
      ORN: AfricaZone,
      OSL: EuropeZone,
      OTP: EuropeZone,
      OUA: AfricaZone,
      PAT: AsiaZone,
      PBH: AsiaZone,
      PBM: SouthAmericaZone,
      PDX: NorthAmericaZone,
      PER: OceaniaZone,
      PHL: NorthAmericaZone,
      PHX: NorthAmericaZone,
      PIT: NorthAmericaZone,
      PKX: AsiaZone,
      PMO: EuropeZone,
      PMW: SouthAmericaZone,
      PNH: AsiaZone,
      POA: SouthAmericaZone,
      POS: SouthAmericaZone,
      PPT: OceaniaZone,
      PRG: EuropeZone,
      PTY: SouthAmericaZone,
      QRO: NorthAmericaZone,
      QWJ: SouthAmericaZone,
      RAO: SouthAmericaZone,
      RDU: NorthAmericaZone,
      REC: SouthAmericaZone,
      RIC: NorthAmericaZone,
      RIX: EuropeZone,
      RUH: AsiaZone,
      RUN: AfricaZone,
      SAN: NorthAmericaZone,
      SAP: SouthAmericaZone,
      SAT: NorthAmericaZone,
      SCL: SouthAmericaZone,
      SDQ: NorthAmericaZone,
      SEA: NorthAmericaZone,
      SFO: NorthAmericaZone,
      SGN: AsiaZone,
      SHA: AsiaZone,
      SIN: AsiaZone,
      SJC: NorthAmericaZone,
      SJK: SouthAmericaZone,
      SJO: SouthAmericaZone,
      SJP: SouthAmericaZone,
      SJU: NorthAmericaZone,
      SJW: AsiaZone,
      SKG: EuropeZone,
      SKP: EuropeZone,
      SLC: NorthAmericaZone,
      SMF: NorthAmericaZone,
      SOD: SouthAmericaZone,
      SOF: EuropeZone,
      SSA: SouthAmericaZone,
      STI: NorthAmericaZone,
      STL: NorthAmericaZone,
      STR: EuropeZone,
      SUV: OceaniaZone,
      SYD: OceaniaZone,
      SZX: AsiaZone,
      TAO: AsiaZone,
      TBS: EuropeZone,
      TEN: AsiaZone,
      TGU: SouthAmericaZone,
      TIA: EuropeZone,
      TLH: NorthAmericaZone,
      TLL: EuropeZone,
      TLV: AsiaZone,
      TNA: AsiaZone,
      TNR: AfricaZone,
      TPA: NorthAmericaZone,
      TPE: AsiaZone,
      TUN: AfricaZone,
      TXL: EuropeZone,
      TYN: AsiaZone,
      UDI: SouthAmericaZone,
      UIO: SouthAmericaZone,
      ULN: AsiaZone,
      URT: AsiaZone,
      VCP: SouthAmericaZone,
      VIE: EuropeZone,
      VIX: SouthAmericaZone,
      VNO: EuropeZone,
      VTE: AsiaZone,
      WAW: EuropeZone,
      WDH: AfricaZone,
      XAP: SouthAmericaZone,
      XFN: AsiaZone,
      XIY: AsiaZone,
      XNH: AsiaZone,
      XNN: AsiaZone,
      YHZ: NorthAmericaZone,
      YOW: NorthAmericaZone,
      YUL: NorthAmericaZone,
      YVR: NorthAmericaZone,
      YWG: NorthAmericaZone,
      YXE: NorthAmericaZone,
      YYC: NorthAmericaZone,
      YYZ: NorthAmericaZone,
      ZAG: EuropeZone,
      ZDM: AsiaZone,
      ZRH: EuropeZone,
    }

    const continentMap = {
      NA: NorthAmericaURL,
      EU: EuropeURL,
      AS: AsiaURL,
      OC: OceaniaURL,
      SA: SouthAmericaURL,
      AF: AfricaURL,
    }

    // Use the cf object to obtain the colo of the request
    // colo: The three-letter IATA ↗ airport code of the data center that the request hit, for example, "DFW".
    // more on the cf object: https://developers.cloudflare.com/workers/runtime-apis/request#incomingrequestcfproperties
    const continent = mapped[request.cf.colo] ?? EuropeZone
    const path = new URL(request.url).pathname
    // If country is not null and is defined in the country map above, redirect.
    if (continent != null && continent in continentMap) {
      const baseUrl = continentMap[continent]
      // Remove this logging statement from your final output.
      console.log(
        `Based on ${continent}-based request, your user would go to ${baseUrl}${path}.`,
      )
      return fetch(`${baseUrl}${path}`, request)

      // If request country not in map, return another page.
    }
    return fetch(request)
  },
}
