/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'

declare module 'vue-router' {
  interface TypesConfig {
    ParamParsers: never
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    '/[...all]': RouteRecordInfo<
      '/[...all]',
      '/:all(.*)',
      { all: ParamValue<true> },
      { all: ParamValue<false> },
      | never
    >,
    '/accountDisabled': RouteRecordInfo<
      '/accountDisabled',
      '/accountDisabled',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/dashboard/': RouteRecordInfo<
      '/admin/dashboard/',
      '/admin/dashboard',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/dashboard/credits': RouteRecordInfo<
      '/admin/dashboard/credits',
      '/admin/dashboard/credits',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/dashboard/plugins': RouteRecordInfo<
      '/admin/dashboard/plugins',
      '/admin/dashboard/plugins',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/dashboard/replication': RouteRecordInfo<
      '/admin/dashboard/replication',
      '/admin/dashboard/replication',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/dashboard/revenue': RouteRecordInfo<
      '/admin/dashboard/revenue',
      '/admin/dashboard/revenue',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/dashboard/updates': RouteRecordInfo<
      '/admin/dashboard/updates',
      '/admin/dashboard/updates',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/dashboard/users': RouteRecordInfo<
      '/admin/dashboard/users',
      '/admin/dashboard/users',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/ApiKeys': RouteRecordInfo<
      '/ApiKeys',
      '/ApiKeys',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/app/[app]': RouteRecordInfo<
      '/app/[app]',
      '/app/:app',
      { app: ParamValue<true> },
      { app: ParamValue<false> },
      | never
    >,
    '/app/[app].access': RouteRecordInfo<
      '/app/[app].access',
      '/app/:app/access',
      { app: ParamValue<true> },
      { app: ParamValue<false> },
      | never
    >,
    '/app/[app].builds': RouteRecordInfo<
      '/app/[app].builds',
      '/app/:app/builds',
      { app: ParamValue<true> },
      { app: ParamValue<false> },
      | never
    >,
    '/app/[app].bundle.[bundle]': RouteRecordInfo<
      '/app/[app].bundle.[bundle]',
      '/app/:app/bundle/:bundle',
      { app: ParamValue<true>, bundle: ParamValue<true> },
      { app: ParamValue<false>, bundle: ParamValue<false> },
      | never
    >,
    '/app/[app].bundle.[bundle].dependencies': RouteRecordInfo<
      '/app/[app].bundle.[bundle].dependencies',
      '/app/:app/bundle/:bundle/dependencies',
      { app: ParamValue<true>, bundle: ParamValue<true> },
      { app: ParamValue<false>, bundle: ParamValue<false> },
      | never
    >,
    '/app/[app].bundle.[bundle].history': RouteRecordInfo<
      '/app/[app].bundle.[bundle].history',
      '/app/:app/bundle/:bundle/history',
      { app: ParamValue<true>, bundle: ParamValue<true> },
      { app: ParamValue<false>, bundle: ParamValue<false> },
      | never
    >,
    '/app/[app].bundle.[bundle].manifest': RouteRecordInfo<
      '/app/[app].bundle.[bundle].manifest',
      '/app/:app/bundle/:bundle/manifest',
      { app: ParamValue<true>, bundle: ParamValue<true> },
      { app: ParamValue<false>, bundle: ParamValue<false> },
      | never
    >,
    '/app/[app].bundle.[bundle].preview': RouteRecordInfo<
      '/app/[app].bundle.[bundle].preview',
      '/app/:app/bundle/:bundle/preview',
      { app: ParamValue<true>, bundle: ParamValue<true> },
      { app: ParamValue<false>, bundle: ParamValue<false> },
      | never
    >,
    '/app/[app].bundles': RouteRecordInfo<
      '/app/[app].bundles',
      '/app/:app/bundles',
      { app: ParamValue<true> },
      { app: ParamValue<false> },
      | never
    >,
    '/app/[app].channel.[channel]': RouteRecordInfo<
      '/app/[app].channel.[channel]',
      '/app/:app/channel/:channel',
      { app: ParamValue<true>, channel: ParamValue<true> },
      { app: ParamValue<false>, channel: ParamValue<false> },
      | never
    >,
    '/app/[app].channel.[channel].devices': RouteRecordInfo<
      '/app/[app].channel.[channel].devices',
      '/app/:app/channel/:channel/devices',
      { app: ParamValue<true>, channel: ParamValue<true> },
      { app: ParamValue<false>, channel: ParamValue<false> },
      | never
    >,
    '/app/[app].channel.[channel].history': RouteRecordInfo<
      '/app/[app].channel.[channel].history',
      '/app/:app/channel/:channel/history',
      { app: ParamValue<true>, channel: ParamValue<true> },
      { app: ParamValue<false>, channel: ParamValue<false> },
      | never
    >,
    '/app/[app].channel.[channel].statistics': RouteRecordInfo<
      '/app/[app].channel.[channel].statistics',
      '/app/:app/channel/:channel/statistics',
      { app: ParamValue<true>, channel: ParamValue<true> },
      { app: ParamValue<false>, channel: ParamValue<false> },
      | never
    >,
    '/app/[app].channels': RouteRecordInfo<
      '/app/[app].channels',
      '/app/:app/channels',
      { app: ParamValue<true> },
      { app: ParamValue<false> },
      | never
    >,
    '/app/[app].device.[device]': RouteRecordInfo<
      '/app/[app].device.[device]',
      '/app/:app/device/:device',
      { app: ParamValue<true>, device: ParamValue<true> },
      { app: ParamValue<false>, device: ParamValue<false> },
      | never
    >,
    '/app/[app].device.[device].deployments': RouteRecordInfo<
      '/app/[app].device.[device].deployments',
      '/app/:app/device/:device/deployments',
      { app: ParamValue<true>, device: ParamValue<true> },
      { app: ParamValue<false>, device: ParamValue<false> },
      | never
    >,
    '/app/[app].device.[device].logs': RouteRecordInfo<
      '/app/[app].device.[device].logs',
      '/app/:app/device/:device/logs',
      { app: ParamValue<true>, device: ParamValue<true> },
      { app: ParamValue<false>, device: ParamValue<false> },
      | never
    >,
    '/app/[app].devices': RouteRecordInfo<
      '/app/[app].devices',
      '/app/:app/devices',
      { app: ParamValue<true> },
      { app: ParamValue<false> },
      | never
    >,
    '/app/[app].info': RouteRecordInfo<
      '/app/[app].info',
      '/app/:app/info',
      { app: ParamValue<true> },
      { app: ParamValue<false> },
      | never
    >,
    '/app/[app].logs': RouteRecordInfo<
      '/app/[app].logs',
      '/app/:app/logs',
      { app: ParamValue<true> },
      { app: ParamValue<false> },
      | never
    >,
    '/app/[package].bundles.new': RouteRecordInfo<
      '/app/[package].bundles.new',
      '/app/:package/bundles/new',
      { package: ParamValue<true> },
      { package: ParamValue<false> },
      | never
    >,
    '/app/modules': RouteRecordInfo<
      '/app/modules',
      '/app/modules',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/app/modules_test': RouteRecordInfo<
      '/app/modules_test',
      '/app/modules_test',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/app/new': RouteRecordInfo<
      '/app/new',
      '/app/new',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/apps': RouteRecordInfo<
      '/apps',
      '/apps',
      Record<never, never>,
      Record<never, never>,
      | '/apps/new'
    >,
    '/apps/new': RouteRecordInfo<
      '/apps/new',
      '/apps/new',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/confirm-signup': RouteRecordInfo<
      '/confirm-signup',
      '/confirm-signup',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/dashboard': RouteRecordInfo<
      '/dashboard',
      '/dashboard',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/delete_account': RouteRecordInfo<
      '/delete_account',
      '/delete_account',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/demo_dialog': RouteRecordInfo<
      '/demo_dialog',
      '/demo_dialog',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/forgot_password': RouteRecordInfo<
      '/forgot_password',
      '/forgot_password',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/invitation': RouteRecordInfo<
      '/invitation',
      '/invitation',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/log-as/[userId]': RouteRecordInfo<
      '/log-as/[userId]',
      '/log-as/:userId',
      { userId: ParamValue<true> },
      { userId: ParamValue<false> },
      | never
    >,
    '/login': RouteRecordInfo<
      '/login',
      '/login',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/onboarding/set_password': RouteRecordInfo<
      '/onboarding/set_password',
      '/onboarding/set_password',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/register': RouteRecordInfo<
      '/register',
      '/register',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/resend_email': RouteRecordInfo<
      '/resend_email',
      '/resend_email',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/scan': RouteRecordInfo<
      '/scan',
      '/scan',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settings/account/': RouteRecordInfo<
      '/settings/account/',
      '/settings/account',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settings/account/ChangePassword': RouteRecordInfo<
      '/settings/account/ChangePassword',
      '/settings/account/change-password',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settings/account/Notifications': RouteRecordInfo<
      '/settings/account/Notifications',
      '/settings/account/Notifications',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settings/organization/': RouteRecordInfo<
      '/settings/organization/',
      '/settings/organization',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settings/organization/Security': RouteRecordInfo<
      '/settings/organization/Security',
      '/settings/organization/security',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settings/organization/AuditLogs': RouteRecordInfo<
      '/settings/organization/AuditLogs',
      '/settings/organization/AuditLogs',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settings/organization/Credits': RouteRecordInfo<
      '/settings/organization/Credits',
      '/settings/organization/Credits',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settings/organization/DeleteOrgDialog': RouteRecordInfo<
      '/settings/organization/DeleteOrgDialog',
      '/settings/organization/DeleteOrgDialog',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settings/organization/Members': RouteRecordInfo<
      '/settings/organization/Members',
      '/settings/organization/Members',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settings/organization/Notifications': RouteRecordInfo<
      '/settings/organization/Notifications',
      '/settings/organization/Notifications',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settings/organization/Plans': RouteRecordInfo<
      '/settings/organization/Plans',
      '/settings/organization/Plans',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settings/organization/Usage': RouteRecordInfo<
      '/settings/organization/Usage',
      '/settings/organization/Usage',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settings/organization/Webhooks': RouteRecordInfo<
      '/settings/organization/Webhooks',
      '/settings/organization/Webhooks',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/Webhooks': RouteRecordInfo<
      '/Webhooks',
      '/Webhooks',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/[...all].vue': {
      routes:
        | '/[...all]'
      views:
        | never
    }
    'src/pages/accountDisabled.vue': {
      routes:
        | '/accountDisabled'
      views:
        | never
    }
    'src/pages/admin/dashboard/index.vue': {
      routes:
        | '/admin/dashboard/'
      views:
        | never
    }
    'src/pages/admin/dashboard/credits.vue': {
      routes:
        | '/admin/dashboard/credits'
      views:
        | never
    }
    'src/pages/admin/dashboard/plugins.vue': {
      routes:
        | '/admin/dashboard/plugins'
      views:
        | never
    }
    'src/pages/admin/dashboard/replication.vue': {
      routes:
        | '/admin/dashboard/replication'
      views:
        | never
    }
    'src/pages/admin/dashboard/revenue.vue': {
      routes:
        | '/admin/dashboard/revenue'
      views:
        | never
    }
    'src/pages/admin/dashboard/updates.vue': {
      routes:
        | '/admin/dashboard/updates'
      views:
        | never
    }
    'src/pages/admin/dashboard/users.vue': {
      routes:
        | '/admin/dashboard/users'
      views:
        | never
    }
    'src/pages/ApiKeys.vue': {
      routes:
        | '/ApiKeys'
      views:
        | never
    }
    'src/pages/app/[app].vue': {
      routes:
        | '/app/[app]'
      views:
        | never
    }
    'src/pages/app/[app].access.vue': {
      routes:
        | '/app/[app].access'
      views:
        | never
    }
    'src/pages/app/[app].builds.vue': {
      routes:
        | '/app/[app].builds'
      views:
        | never
    }
    'src/pages/app/[app].bundle.[bundle].vue': {
      routes:
        | '/app/[app].bundle.[bundle]'
      views:
        | never
    }
    'src/pages/app/[app].bundle.[bundle].dependencies.vue': {
      routes:
        | '/app/[app].bundle.[bundle].dependencies'
      views:
        | never
    }
    'src/pages/app/[app].bundle.[bundle].history.vue': {
      routes:
        | '/app/[app].bundle.[bundle].history'
      views:
        | never
    }
    'src/pages/app/[app].bundle.[bundle].manifest.vue': {
      routes:
        | '/app/[app].bundle.[bundle].manifest'
      views:
        | never
    }
    'src/pages/app/[app].bundle.[bundle].preview.vue': {
      routes:
        | '/app/[app].bundle.[bundle].preview'
      views:
        | never
    }
    'src/pages/app/[app].bundles.vue': {
      routes:
        | '/app/[app].bundles'
      views:
        | never
    }
    'src/pages/app/[app].channel.[channel].vue': {
      routes:
        | '/app/[app].channel.[channel]'
      views:
        | never
    }
    'src/pages/app/[app].channel.[channel].devices.vue': {
      routes:
        | '/app/[app].channel.[channel].devices'
      views:
        | never
    }
    'src/pages/app/[app].channel.[channel].history.vue': {
      routes:
        | '/app/[app].channel.[channel].history'
      views:
        | never
    }
    'src/pages/app/[app].channel.[channel].statistics.vue': {
      routes:
        | '/app/[app].channel.[channel].statistics'
      views:
        | never
    }
    'src/pages/app/[app].channels.vue': {
      routes:
        | '/app/[app].channels'
      views:
        | never
    }
    'src/pages/app/[app].device.[device].vue': {
      routes:
        | '/app/[app].device.[device]'
      views:
        | never
    }
    'src/pages/app/[app].device.[device].deployments.vue': {
      routes:
        | '/app/[app].device.[device].deployments'
      views:
        | never
    }
    'src/pages/app/[app].device.[device].logs.vue': {
      routes:
        | '/app/[app].device.[device].logs'
      views:
        | never
    }
    'src/pages/app/[app].devices.vue': {
      routes:
        | '/app/[app].devices'
      views:
        | never
    }
    'src/pages/app/[app].info.vue': {
      routes:
        | '/app/[app].info'
      views:
        | never
    }
    'src/pages/app/[app].logs.vue': {
      routes:
        | '/app/[app].logs'
      views:
        | never
    }
    'src/pages/app/[package].bundles.new.vue': {
      routes:
        | '/app/[package].bundles.new'
      views:
        | never
    }
    'src/pages/app/modules.vue': {
      routes:
        | '/app/modules'
      views:
        | never
    }
    'src/pages/app/modules_test.vue': {
      routes:
        | '/app/modules_test'
      views:
        | never
    }
    'src/pages/app/new.vue': {
      routes:
        | '/app/new'
      views:
        | never
    }
    'src/pages/apps.vue': {
      routes:
        | '/apps'
        | '/apps/new'
      views:
        | 'default'
    }
    'src/pages/apps/new.vue': {
      routes:
        | '/apps/new'
      views:
        | never
    }
    'src/pages/confirm-signup.vue': {
      routes:
        | '/confirm-signup'
      views:
        | never
    }
    'src/pages/dashboard.vue': {
      routes:
        | '/dashboard'
      views:
        | never
    }
    'src/pages/delete_account.vue': {
      routes:
        | '/delete_account'
      views:
        | never
    }
    'src/pages/demo_dialog.vue': {
      routes:
        | '/demo_dialog'
      views:
        | never
    }
    'src/pages/forgot_password.vue': {
      routes:
        | '/forgot_password'
      views:
        | never
    }
    'src/pages/invitation.vue': {
      routes:
        | '/invitation'
      views:
        | never
    }
    'src/pages/log-as/[userId].vue': {
      routes:
        | '/log-as/[userId]'
      views:
        | never
    }
    'src/pages/login.vue': {
      routes:
        | '/login'
      views:
        | never
    }
    'src/pages/onboarding/set_password.vue': {
      routes:
        | '/onboarding/set_password'
      views:
        | never
    }
    'src/pages/register.vue': {
      routes:
        | '/register'
      views:
        | never
    }
    'src/pages/resend_email.vue': {
      routes:
        | '/resend_email'
      views:
        | never
    }
    'src/pages/scan.vue': {
      routes:
        | '/scan'
      views:
        | never
    }
    'src/pages/settings/account/index.vue': {
      routes:
        | '/settings/account/'
      views:
        | never
    }
    'src/pages/settings/account/ChangePassword.vue': {
      routes:
        | '/settings/account/ChangePassword'
      views:
        | never
    }
    'src/pages/settings/account/Notifications.vue': {
      routes:
        | '/settings/account/Notifications'
      views:
        | never
    }
    'src/pages/settings/organization/index.vue': {
      routes:
        | '/settings/organization/'
      views:
        | never
    }
    'src/pages/settings/organization/Security.vue': {
      routes:
        | '/settings/organization/Security'
      views:
        | never
    }
    'src/pages/settings/organization/AuditLogs.vue': {
      routes:
        | '/settings/organization/AuditLogs'
      views:
        | never
    }
    'src/pages/settings/organization/Credits.vue': {
      routes:
        | '/settings/organization/Credits'
      views:
        | never
    }
    'src/pages/settings/organization/DeleteOrgDialog.vue': {
      routes:
        | '/settings/organization/DeleteOrgDialog'
      views:
        | never
    }
    'src/pages/settings/organization/Members.vue': {
      routes:
        | '/settings/organization/Members'
      views:
        | never
    }
    'src/pages/settings/organization/Notifications.vue': {
      routes:
        | '/settings/organization/Notifications'
      views:
        | never
    }
    'src/pages/settings/organization/Plans.vue': {
      routes:
        | '/settings/organization/Plans'
      views:
        | never
    }
    'src/pages/settings/organization/Usage.vue': {
      routes:
        | '/settings/organization/Usage'
      views:
        | never
    }
    'src/pages/settings/organization/Webhooks.vue': {
      routes:
        | '/settings/organization/Webhooks'
      views:
        | never
    }
    'src/pages/Webhooks.vue': {
      routes:
        | '/Webhooks'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
