/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/[...all]': RouteRecordInfo<'/[...all]', '/:all(.*)', { all: ParamValue<true> }, { all: ParamValue<false> }>,
    '/ApiKeys': RouteRecordInfo<'/ApiKeys', '/ApiKeys', Record<never, never>, Record<never, never>>,
    '/app/': RouteRecordInfo<'/app/', '/app', Record<never, never>, Record<never, never>>,
    '/app/modules': RouteRecordInfo<'/app/modules', '/app/modules', Record<never, never>, Record<never, never>>,
    '/app/modules_test': RouteRecordInfo<'/app/modules_test', '/app/modules_test', Record<never, never>, Record<never, never>>,
    '/app/p/[package]': RouteRecordInfo<'/app/p/[package]', '/app/p/:package', { package: ParamValue<true> }, { package: ParamValue<false> }>,
    '/app/p/[package].bundle.[bundle]': RouteRecordInfo<'/app/p/[package].bundle.[bundle]', '/app/p/:package/bundle/:bundle', { package: ParamValue<true>, bundle: ParamValue<true> }, { package: ParamValue<false>, bundle: ParamValue<false> }>,
    '/app/p/[package].channel.[channel]': RouteRecordInfo<'/app/p/[package].channel.[channel]', '/app/p/:package/channel/:channel', { package: ParamValue<true>, channel: ParamValue<true> }, { package: ParamValue<false>, channel: ParamValue<false> }>,
    '/app/p/[package].d.[device]': RouteRecordInfo<'/app/p/[package].d.[device]', '/app/p/:package/d/:device', { package: ParamValue<true>, device: ParamValue<true> }, { package: ParamValue<false>, device: ParamValue<false> }>,
    '/confirm-signup': RouteRecordInfo<'/confirm-signup', '/confirm-signup', Record<never, never>, Record<never, never>>,
    '/delete_account': RouteRecordInfo<'/delete_account', '/delete_account', Record<never, never>, Record<never, never>>,
    '/forgot_password': RouteRecordInfo<'/forgot_password', '/forgot_password', Record<never, never>, Record<never, never>>,
    '/invitation': RouteRecordInfo<'/invitation', '/invitation', Record<never, never>, Record<never, never>>,
    '/login': RouteRecordInfo<'/login', '/login', Record<never, never>, Record<never, never>>,
    '/onboarding/activation': RouteRecordInfo<'/onboarding/activation', '/onboarding/activation', Record<never, never>, Record<never, never>>,
    '/onboarding/confirm_email': RouteRecordInfo<'/onboarding/confirm_email', '/onboarding/confirm_email', Record<never, never>, Record<never, never>>,
    '/onboarding/set_password': RouteRecordInfo<'/onboarding/set_password', '/onboarding/set_password', Record<never, never>, Record<never, never>>,
    '/onboarding/verify_email': RouteRecordInfo<'/onboarding/verify_email', '/onboarding/verify_email', Record<never, never>, Record<never, never>>,
    '/register': RouteRecordInfo<'/register', '/register', Record<never, never>, Record<never, never>>,
    '/resend_email': RouteRecordInfo<'/resend_email', '/resend_email', Record<never, never>, Record<never, never>>,
    '/settings/Account': RouteRecordInfo<'/settings/Account', '/settings/Account', Record<never, never>, Record<never, never>>,
    '/settings/ChangePassword': RouteRecordInfo<'/settings/ChangePassword', '/settings/ChangePassword', Record<never, never>, Record<never, never>>,
    '/settings/Notifications': RouteRecordInfo<'/settings/Notifications', '/settings/Notifications', Record<never, never>, Record<never, never>>,
    '/settings/organization/': RouteRecordInfo<'/settings/organization/', '/settings/organization', Record<never, never>, Record<never, never>>,
    '/settings/organization/Members': RouteRecordInfo<'/settings/organization/Members', '/settings/organization/Members', Record<never, never>, Record<never, never>>,
    '/settings/organization/Plans': RouteRecordInfo<'/settings/organization/Plans', '/settings/organization/Plans', Record<never, never>, Record<never, never>>,
    '/settings/organization/Usage': RouteRecordInfo<'/settings/organization/Usage', '/settings/organization/Usage', Record<never, never>, Record<never, never>>,
  }
}
