DROP FUNCTION IF EXISTS public.get_total_stats_v2(dateid character varying);
DROP FUNCTION IF EXISTS public.get_total_stats_v2(userid uuid, dateid character varying);
DROP FUNCTION IF EXISTS public.get_total_stats_v3();
DROP FUNCTION IF EXISTS public.get_total_stats_v3(userid uuid);
DROP FUNCTION IF EXISTS public.get_total_stats_v4(userid uuid);
DROP FUNCTION IF EXISTS public.get_orgs_v2();
DROP FUNCTION IF EXISTS public.get_orgs(userid uuid);
DROP FUNCTION IF EXISTS public.exist_app(appid character varying);
DROP FUNCTION IF EXISTS public.is_good_plan_v3();
DROP FUNCTION IF EXISTS public.is_good_plan_v3(userid uuid);
DROP FUNCTION IF EXISTS public.is_good_plan_v4();
DROP FUNCTION IF EXISTS public.is_good_plan_v4(userid uuid);
