CREATE OR REPLACE FUNCTION public.rbac_perm_org_create()
RETURNS text
LANGUAGE sql
IMMUTABLE
SET search_path = ''
AS $$
  SELECT 'org.create'::text
$$;

ALTER FUNCTION public.rbac_perm_org_create() OWNER TO postgres;
REVOKE ALL ON FUNCTION public.rbac_perm_org_create() FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.rbac_perm_org_create() TO anon;
GRANT EXECUTE ON FUNCTION public.rbac_perm_org_create() TO authenticated;
GRANT EXECUTE ON FUNCTION public.rbac_perm_org_create() TO service_role;

COMMENT ON FUNCTION public.rbac_perm_org_create() IS
  'Global API-key permission for creating a new organization before an org-scoped RBAC binding can exist.';

CREATE TABLE IF NOT EXISTS public.apikey_global_permissions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  apikey_rbac_id uuid NOT NULL REFERENCES public.apikeys(rbac_id) ON DELETE CASCADE,
  permission_key text NOT NULL,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  granted_by uuid REFERENCES public.users(id) ON DELETE SET NULL,
  reason text,
  CONSTRAINT apikey_global_permissions_permission_key_not_empty CHECK (permission_key <> ''),
  CONSTRAINT apikey_global_permissions_rbac_permission_unique UNIQUE (apikey_rbac_id, permission_key)
);

ALTER TABLE public.apikey_global_permissions OWNER TO postgres;
ALTER TABLE public.apikey_global_permissions ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON TABLE public.apikey_global_permissions FROM PUBLIC;
REVOKE ALL ON TABLE public.apikey_global_permissions FROM anon;
REVOKE ALL ON TABLE public.apikey_global_permissions FROM authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.apikey_global_permissions TO service_role;
GRANT USAGE, SELECT ON SEQUENCE public.apikey_global_permissions_id_seq TO service_role;

CREATE POLICY "Deny select on apikey_global_permissions"
ON public.apikey_global_permissions
AS RESTRICTIVE
FOR SELECT
TO anon, authenticated
USING (false);

CREATE POLICY "Deny insert on apikey_global_permissions"
ON public.apikey_global_permissions
AS RESTRICTIVE
FOR INSERT
TO anon, authenticated
WITH CHECK (false);

CREATE POLICY "Deny update on apikey_global_permissions"
ON public.apikey_global_permissions
AS RESTRICTIVE
FOR UPDATE
TO anon, authenticated
USING (false)
WITH CHECK (false);

CREATE POLICY "Deny delete on apikey_global_permissions"
ON public.apikey_global_permissions
AS RESTRICTIVE
FOR DELETE
TO anon, authenticated
USING (false);

COMMENT ON TABLE public.apikey_global_permissions IS
  'Global permissions for API keys where no org/app/channel target exists yet. Currently used to grandfather org creation for existing write-capable keys without granting it to future keys by default.';

INSERT INTO public.apikey_global_permissions (
  apikey_rbac_id,
  permission_key,
  granted_by,
  reason
)
SELECT
  apikeys.rbac_id,
  public.rbac_perm_org_create(),
  apikeys.user_id,
  'Backfilled for org-scoped write-capable API keys that existed before org.create became explicit'
FROM public.apikeys
WHERE EXISTS (
  SELECT 1
  FROM public.role_bindings
  JOIN public.roles ON public.roles.id = public.role_bindings.role_id
  WHERE public.role_bindings.principal_type = public.rbac_principal_apikey()
    AND public.role_bindings.principal_id = apikeys.rbac_id
    AND public.role_bindings.scope_type = public.rbac_scope_org()
    AND (
      public.role_bindings.expires_at IS NULL
      OR public.role_bindings.expires_at > pg_catalog.now()
    )
    AND public.roles.name IN (
      public.rbac_role_org_super_admin(),
      public.rbac_role_org_admin()
    )
)
ON CONFLICT (apikey_rbac_id, permission_key) DO NOTHING;

CREATE OR REPLACE FUNCTION public.apikey_has_current_org_create_capability(
  p_apikey_rbac_id uuid
)
RETURNS boolean
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = ''
AS $$
  SELECT EXISTS (
    SELECT 1
    FROM public.role_bindings AS rb
    JOIN public.roles AS r ON r.id = rb.role_id
    WHERE rb.principal_type = public.rbac_principal_apikey()
      AND rb.principal_id = p_apikey_rbac_id
      AND rb.scope_type = public.rbac_scope_org()
      AND r.scope_type = public.rbac_scope_org()
      AND (
        rb.expires_at IS NULL
        OR rb.expires_at > pg_catalog.now()
      )
      AND r.name IN (
        public.rbac_role_org_super_admin(),
        public.rbac_role_org_admin()
      )
  )
$$;

ALTER FUNCTION public.apikey_has_current_org_create_capability(uuid) OWNER TO postgres;
REVOKE ALL ON FUNCTION public.apikey_has_current_org_create_capability(uuid) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.apikey_has_current_org_create_capability(uuid) TO service_role;

COMMENT ON FUNCTION public.apikey_has_current_org_create_capability(uuid) IS
  'Private helper ensuring org.create grants only remain effective while the API key still has a current org-scoped write-capable RBAC binding.';

CREATE OR REPLACE FUNCTION public.apikey_has_global_permission(
  p_apikey text,
  p_permission_key text
)
RETURNS boolean
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
  v_api_key public.apikeys%ROWTYPE;
BEGIN
  IF p_apikey IS NULL OR p_apikey = '' OR p_permission_key IS NULL OR p_permission_key = '' THEN
    RETURN false;
  END IF;

  SELECT *
  INTO v_api_key
  FROM public.find_apikey_by_value(p_apikey)
  LIMIT 1;

  IF v_api_key.id IS NULL OR public.is_apikey_expired(v_api_key.expires_at) THEN
    RETURN false;
  END IF;

  IF NOT EXISTS (
    SELECT 1
    FROM public.apikey_global_permissions AS agp
    WHERE agp.apikey_rbac_id = v_api_key.rbac_id
      AND agp.permission_key = p_permission_key
  ) THEN
    RETURN false;
  END IF;

  IF p_permission_key = public.rbac_perm_org_create() THEN
    RETURN public.apikey_has_current_org_create_capability(v_api_key.rbac_id);
  END IF;

  RETURN true;
END;
$$;

ALTER FUNCTION public.apikey_has_global_permission(text, text) OWNER TO postgres;
REVOKE ALL ON FUNCTION public.apikey_has_global_permission(text, text) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.apikey_has_global_permission(text, text) TO service_role;

COMMENT ON FUNCTION public.apikey_has_global_permission(text, text) IS
  'Service-role helper that checks global API-key permissions such as org.create using the supplied key value, including hashed-key lookup.';

CREATE OR REPLACE FUNCTION public.get_identity_for_apikey_creation()
RETURNS uuid
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
  auth_uid uuid;
BEGIN
  SELECT auth.uid() INTO auth_uid;
  IF auth_uid IS NOT NULL THEN
    RETURN auth_uid;
  END IF;

  PERFORM public.pg_log('deny: APIKEY_CREATE_WITH_API_KEY_DISABLED', '{}'::jsonb);
  RETURN NULL;
END;
$$;

ALTER FUNCTION public.get_identity_for_apikey_creation() OWNER TO postgres;
REVOKE ALL ON FUNCTION public.get_identity_for_apikey_creation() FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.get_identity_for_apikey_creation() TO anon;
GRANT EXECUTE ON FUNCTION public.get_identity_for_apikey_creation() TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_identity_for_apikey_creation() TO service_role;

COMMENT ON FUNCTION public.get_identity_for_apikey_creation() IS
  'Returns auth.uid() for JWT callers; API-key creation of API keys stays disabled even when org.create is granted.';

CREATE OR REPLACE FUNCTION public.bind_creating_apikey_to_org_on_create()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
  api_key_text text;
  api_key public.apikeys%ROWTYPE;
  org_super_admin_role_id uuid;
BEGIN
  SELECT public.get_apikey_header() INTO api_key_text;
  IF api_key_text IS NULL THEN
    RETURN NEW;
  END IF;

  SELECT *
  INTO api_key
  FROM public.find_apikey_by_value(api_key_text)
  LIMIT 1;

  IF api_key.id IS NULL
    OR public.is_apikey_expired(api_key.expires_at)
    OR api_key.user_id IS DISTINCT FROM NEW.created_by
  THEN
    RETURN NEW;
  END IF;

  IF NOT EXISTS (
    SELECT 1
    FROM public.apikey_global_permissions AS agp
    WHERE agp.apikey_rbac_id = api_key.rbac_id
      AND agp.permission_key = public.rbac_perm_org_create()
  )
  OR NOT public.apikey_has_current_org_create_capability(api_key.rbac_id) THEN
    RETURN NEW;
  END IF;

  SELECT roles.id
  INTO org_super_admin_role_id
  FROM public.roles
  WHERE roles.name = public.rbac_role_org_super_admin()
    AND roles.scope_type = public.rbac_scope_org()
  LIMIT 1;

  IF org_super_admin_role_id IS NULL THEN
    RAISE EXCEPTION 'org_super_admin role not found';
  END IF;

  INSERT INTO public.role_bindings (
    principal_type,
    principal_id,
    role_id,
    scope_type,
    org_id,
    granted_by,
    granted_at,
    reason,
    is_direct
  )
  VALUES (
    public.rbac_principal_apikey(),
    api_key.rbac_id,
    org_super_admin_role_id,
    public.rbac_scope_org(),
    NEW.id,
    NEW.created_by,
    pg_catalog.now(),
    'Auto-granted to API key on org creation',
    true
  )
  ON CONFLICT DO NOTHING;

  RETURN NEW;
END;
$$;

ALTER FUNCTION public.bind_creating_apikey_to_org_on_create() OWNER TO postgres;
REVOKE ALL ON FUNCTION public.bind_creating_apikey_to_org_on_create() FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.bind_creating_apikey_to_org_on_create() TO service_role;

DROP TRIGGER IF EXISTS bind_creating_apikey_to_org_on_create ON public.orgs;
CREATE TRIGGER bind_creating_apikey_to_org_on_create
AFTER INSERT ON public.orgs
FOR EACH ROW
EXECUTE FUNCTION public.bind_creating_apikey_to_org_on_create();

DROP POLICY IF EXISTS "Allow insert org for user" ON public.orgs;
DROP POLICY IF EXISTS "Allow insert org for apikey or user" ON public.orgs;
DROP POLICY IF EXISTS "Allow insert org for user or apikey with org.create" ON public.orgs;
CREATE POLICY "Allow insert org for user"
ON public.orgs
FOR INSERT
TO authenticated
WITH CHECK (
  created_by = (SELECT public.get_identity_for_apikey_creation())
);
