ALTER TABLE public.global_stats
ADD COLUMN IF NOT EXISTS trial_extended_orgs integer DEFAULT 0 NOT NULL,
ADD COLUMN IF NOT EXISTS trial_extended_subscribed_orgs integer DEFAULT 0 NOT NULL;

COMMENT ON COLUMN public.global_stats.trial_extended_orgs IS
  'Number of organizations whose trial was extended during the UTC day.';

COMMENT ON COLUMN public.global_stats.trial_extended_subscribed_orgs IS
  'Number of organizations with a recorded trial extension that first subscribed during the UTC day.';

CREATE TABLE IF NOT EXISTS public.trial_extension_events (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  org_id uuid NOT NULL REFERENCES public.orgs(id) ON DELETE CASCADE,
  customer_id character varying NOT NULL REFERENCES public.stripe_info(customer_id) ON DELETE CASCADE,
  previous_trial_at timestamp with time zone NOT NULL,
  new_trial_at timestamp with time zone NOT NULL,
  extension_days integer NOT NULL
);

ALTER TABLE public.trial_extension_events OWNER TO "postgres";

COMMENT ON TABLE public.trial_extension_events IS
  'Internal event log for exact daily trial extension metrics.';

COMMENT ON COLUMN public.trial_extension_events.extension_days IS
  'Days added beyond the default 15-day trial window after the extension update.';

ALTER TABLE public.trial_extension_events ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Deny select on trial_extension_events"
ON public.trial_extension_events
AS RESTRICTIVE
FOR SELECT
TO anon, authenticated
USING (false);

CREATE POLICY "Deny insert on trial_extension_events"
ON public.trial_extension_events
AS RESTRICTIVE
FOR INSERT
TO anon, authenticated
WITH CHECK (false);

CREATE POLICY "Deny update on trial_extension_events"
ON public.trial_extension_events
AS RESTRICTIVE
FOR UPDATE
TO anon, authenticated
USING (false)
WITH CHECK (false);

CREATE POLICY "Deny delete on trial_extension_events"
ON public.trial_extension_events
AS RESTRICTIVE
FOR DELETE
TO anon, authenticated
USING (false);

CREATE INDEX IF NOT EXISTS idx_trial_extension_events_created_at
ON public.trial_extension_events(created_at);

CREATE INDEX IF NOT EXISTS idx_trial_extension_events_org_created
ON public.trial_extension_events(org_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_trial_extension_events_customer_created
ON public.trial_extension_events(customer_id, created_at DESC);

REVOKE ALL ON TABLE public.trial_extension_events FROM PUBLIC;
REVOKE ALL ON TABLE public.trial_extension_events FROM anon;
REVOKE ALL ON TABLE public.trial_extension_events FROM authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.trial_extension_events TO service_role;

REVOKE ALL ON SEQUENCE public.trial_extension_events_id_seq FROM PUBLIC;
REVOKE ALL ON SEQUENCE public.trial_extension_events_id_seq FROM anon;
REVOKE ALL ON SEQUENCE public.trial_extension_events_id_seq FROM authenticated;
GRANT USAGE, SELECT ON SEQUENCE public.trial_extension_events_id_seq TO service_role;

CREATE OR REPLACE FUNCTION public.record_trial_extension_event()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
  org_id_for_event uuid;
  extension_days_for_event integer;
BEGIN
  IF NEW.trial_at <= OLD.trial_at THEN
    RETURN NEW;
  END IF;

  SELECT
    public.orgs.id,
    GREATEST(0, (NEW.trial_at::date - public.orgs.created_at::date - 15))::integer
  INTO org_id_for_event, extension_days_for_event
  FROM public.orgs
  WHERE public.orgs.customer_id = NEW.customer_id
  LIMIT 1;

  IF org_id_for_event IS NULL OR extension_days_for_event <= 0 THEN
    RETURN NEW;
  END IF;

  INSERT INTO public.trial_extension_events (
    org_id,
    customer_id,
    previous_trial_at,
    new_trial_at,
    extension_days
  )
  VALUES (
    org_id_for_event,
    NEW.customer_id,
    OLD.trial_at,
    NEW.trial_at,
    extension_days_for_event
  );

  RETURN NEW;
END;
$$;

ALTER FUNCTION public.record_trial_extension_event() OWNER TO "postgres";
REVOKE ALL ON FUNCTION public.record_trial_extension_event() FROM PUBLIC;
REVOKE ALL ON FUNCTION public.record_trial_extension_event() FROM anon;
REVOKE ALL ON FUNCTION public.record_trial_extension_event() FROM authenticated;
GRANT ALL ON FUNCTION public.record_trial_extension_event() TO service_role;

DROP TRIGGER IF EXISTS record_trial_extension_event_on_stripe_info ON public.stripe_info;
CREATE TRIGGER record_trial_extension_event_on_stripe_info
AFTER UPDATE OF trial_at ON public.stripe_info
FOR EACH ROW
EXECUTE FUNCTION public.record_trial_extension_event();
