require_relative '../../node_modules/@capacitor/ios/scripts/pods_helpers'

platform :ios, '13.0'
use_frameworks!

# workaround to avoid Xcode caching of Pods that requires
# Product -> Clean Build Folder after new Cordova plugins installed
# Requires CocoaPods 1.6 or newer
install! 'cocoapods', :disable_input_output_paths => true

def capacitor_pods
  pod 'Capacitor', :path => '../../node_modules/.pnpm/@capacitor+ios@4.0.1_@capacitor+core@4.0.1/node_modules/@capacitor/ios'
  pod 'CapacitorCordova', :path => '../../node_modules/.pnpm/@capacitor+ios@4.0.1_@capacitor+core@4.0.1/node_modules/@capacitor/ios'
  pod 'CapacitorCommunityHttp', :path => '../../node_modules/.pnpm/@capacitor-community+http@1.4.1/node_modules/@capacitor-community/http'
  pod 'CapacitorCommunityKeepAwake', :path => '../../node_modules/.pnpm/@capacitor-community+keep-awake@3.0.0_@capacitor+core@4.0.1/node_modules/@capacitor-community/keep-awake'
  pod 'CapacitorActionSheet', :path => '../../node_modules/.pnpm/@capacitor+action-sheet@4.0.1_@capacitor+core@4.0.1/node_modules/@capacitor/action-sheet'
  pod 'CapacitorApp', :path => '../../node_modules/.pnpm/@capacitor+app@4.0.1_@capacitor+core@4.0.1/node_modules/@capacitor/app'
  pod 'CapacitorAppLauncher', :path => '../../node_modules/.pnpm/@capacitor+app-launcher@4.0.1_@capacitor+core@4.0.1/node_modules/@capacitor/app-launcher'
  pod 'CapacitorBrowser', :path => '../../node_modules/.pnpm/@capacitor+browser@4.0.1_@capacitor+core@4.0.1/node_modules/@capacitor/browser'
  pod 'CapacitorCamera', :path => '../../node_modules/.pnpm/@capacitor+camera@4.0.1_@capacitor+core@4.0.1/node_modules/@capacitor/camera'
  pod 'CapacitorClipboard', :path => '../../node_modules/.pnpm/@capacitor+clipboard@4.0.1_@capacitor+core@4.0.1/node_modules/@capacitor/clipboard'
  pod 'CapacitorDevice', :path => '../../node_modules/.pnpm/@capacitor+device@4.0.1_@capacitor+core@4.0.1/node_modules/@capacitor/device'
  pod 'CapacitorDialog', :path => '../../node_modules/.pnpm/@capacitor+dialog@4.0.1_@capacitor+core@4.0.1/node_modules/@capacitor/dialog'
  pod 'CapacitorFilesystem', :path => '../../node_modules/.pnpm/@capacitor+filesystem@4.0.1_@capacitor+core@4.0.1/node_modules/@capacitor/filesystem'
  pod 'CapacitorGeolocation', :path => '../../node_modules/.pnpm/@capacitor+geolocation@4.0.1_@capacitor+core@4.0.1/node_modules/@capacitor/geolocation'
  pod 'CapacitorHaptics', :path => '../../node_modules/.pnpm/@capacitor+haptics@4.0.1_@capacitor+core@4.0.1/node_modules/@capacitor/haptics'
  pod 'CapacitorKeyboard', :path => '../../node_modules/.pnpm/@capacitor+keyboard@4.0.1_@capacitor+core@4.0.1/node_modules/@capacitor/keyboard'
  pod 'CapacitorLocalNotifications', :path => '../../node_modules/.pnpm/@capacitor+local-notifications@4.0.1_@capacitor+core@4.0.1/node_modules/@capacitor/local-notifications'
  pod 'CapacitorNetwork', :path => '../../node_modules/.pnpm/@capacitor+network@4.0.1_@capacitor+core@4.0.1/node_modules/@capacitor/network'
  pod 'CapacitorPreferences', :path => '../../node_modules/.pnpm/@capacitor+preferences@4.0.1_@capacitor+core@4.0.1/node_modules/@capacitor/preferences'
  pod 'CapacitorPushNotifications', :path => '../../node_modules/.pnpm/@capacitor+push-notifications@4.0.1_@capacitor+core@4.0.1/node_modules/@capacitor/push-notifications'
  pod 'CapacitorScreenReader', :path => '../../node_modules/.pnpm/@capacitor+screen-reader@4.0.1_@capacitor+core@4.0.1/node_modules/@capacitor/screen-reader'
  pod 'CapacitorShare', :path => '../../node_modules/.pnpm/@capacitor+share@4.0.1_@capacitor+core@4.0.1/node_modules/@capacitor/share'
  pod 'CapacitorSplashScreen', :path => '../../node_modules/.pnpm/@capacitor+splash-screen@4.0.1_@capacitor+core@4.0.1/node_modules/@capacitor/splash-screen'
  pod 'CapacitorStatusBar', :path => '../../node_modules/.pnpm/@capacitor+status-bar@4.0.1_@capacitor+core@4.0.1/node_modules/@capacitor/status-bar'
  pod 'CapacitorTextZoom', :path => '../../node_modules/.pnpm/@capacitor+text-zoom@4.0.1_@capacitor+core@4.0.1/node_modules/@capacitor/text-zoom'
  pod 'CapacitorToast', :path => '../../node_modules/.pnpm/@capacitor+toast@4.0.1_@capacitor+core@4.0.1/node_modules/@capacitor/toast'
  pod 'CapawesomeCapacitorFilePicker', :path => '../../node_modules/.pnpm/@capawesome+capacitor-file-picker@0.4.0_@capacitor+core@4.0.1/node_modules/@capawesome/capacitor-file-picker'
  pod 'CapawesomeCapacitorScreenOrientation', :path => '../../node_modules/.pnpm/@capawesome+capacitor-screen-orientation@2.0.0_@capacitor+core@4.0.1/node_modules/@capawesome/capacitor-screen-orientation'
  pod 'CapgoCapacitorUpdater', :path => '../../node_modules/.pnpm/@capgo+capacitor-updater@4.0.0-alpha.35_@capacitor+core@4.0.1/node_modules/@capgo/capacitor-updater'
  pod 'TeamhiveCapacitorVideoRecorder', :path => '../../node_modules/.pnpm/@teamhive+capacitor-video-recorder@5.0.0_@capacitor+core@4.0.1/node_modules/@teamhive/capacitor-video-recorder'
  pod 'CapacitorFlash', :path => '../../node_modules/.pnpm/capacitor-flash@1.1.3_@capacitor+core@4.0.1/node_modules/capacitor-flash'
  pod 'CapacitorMute', :path => '../../node_modules/.pnpm/capacitor-mute@0.0.4_@capacitor+core@4.0.1/node_modules/capacitor-mute'
  pod 'CapacitorNativeAudio', :path => '../../node_modules/.pnpm/capacitor-native-audio@3.0.2_@capacitor+core@4.0.1/node_modules/capacitor-native-audio'
  pod 'CapacitorNativeBiometric', :path => '../../node_modules/.pnpm/capacitor-native-biometric@4.1.2/node_modules/capacitor-native-biometric'
  pod 'CapacitorPurchases', :path => '../../node_modules/.pnpm/capacitor-purchases@1.2.4_@capacitor+core@4.0.1/node_modules/capacitor-purchases'
  pod 'CapacitorRateApp', :path => '../../node_modules/.pnpm/capacitor-rate-app@2.0.0_@capacitor+core@4.0.1/node_modules/capacitor-rate-app'
  pod 'CapacitorScreenRecorder', :path => '../../node_modules/.pnpm/capacitor-screen-recorder@1.1.5_@capacitor+core@4.0.1/node_modules/capacitor-screen-recorder'
end

target 'App' do
  capacitor_pods
  # Add your Pods here
end


post_install do |installer|
  assertDeploymentTarget(installer)
end
