platform :ios, '12.0'
use_frameworks!

# workaround to avoid Xcode caching of Pods that requires
# Product -> Clean Build Folder after new Cordova plugins installed
# Requires CocoaPods 1.6 or newer
install! 'cocoapods', :disable_input_output_paths => true

def capacitor_pods
  pod 'Capacitor', :path => '../../node_modules/.pnpm/@capacitor+ios@3.3.4_@capacitor+core@3.3.4/node_modules/@capacitor/ios'
  pod 'CapacitorCordova', :path => '../../node_modules/.pnpm/@capacitor+ios@3.3.4_@capacitor+core@3.3.4/node_modules/@capacitor/ios'
  pod 'CapacitorActionSheet', :path => '../../node_modules/.pnpm/@capacitor+action-sheet@1.0.6_@capacitor+core@3.3.4/node_modules/@capacitor/action-sheet'
  pod 'CapacitorApp', :path => '../../node_modules/.pnpm/@capacitor+app@1.0.7_@capacitor+core@3.3.4/node_modules/@capacitor/app'
  pod 'CapacitorAppLauncher', :path => '../../node_modules/.pnpm/@capacitor+app-launcher@1.0.7_@capacitor+core@3.3.4/node_modules/@capacitor/app-launcher'
  pod 'CapacitorBrowser', :path => '../../node_modules/.pnpm/@capacitor+browser@1.0.6_@capacitor+core@3.3.4/node_modules/@capacitor/browser'
  pod 'CapacitorCamera', :path => '../../node_modules/.pnpm/@capacitor+camera@1.2.3_@capacitor+core@3.3.4/node_modules/@capacitor/camera'
  pod 'CapacitorClipboard', :path => '../../node_modules/.pnpm/@capacitor+clipboard@1.0.6_@capacitor+core@3.3.4/node_modules/@capacitor/clipboard'
  pod 'CapacitorDevice', :path => '../../node_modules/.pnpm/@capacitor+device@1.1.1_@capacitor+core@3.3.4/node_modules/@capacitor/device'
  pod 'CapacitorDialog', :path => '../../node_modules/.pnpm/@capacitor+dialog@1.0.6_@capacitor+core@3.3.4/node_modules/@capacitor/dialog'
  pod 'CapacitorFilesystem', :path => '../../node_modules/.pnpm/@capacitor+filesystem@1.0.7_@capacitor+core@3.3.4/node_modules/@capacitor/filesystem'
  pod 'CapacitorGeolocation', :path => '../../node_modules/.pnpm/@capacitor+geolocation@1.3.0_@capacitor+core@3.3.4/node_modules/@capacitor/geolocation'
  pod 'CapacitorHaptics', :path => '../../node_modules/.pnpm/@capacitor+haptics@1.1.3_@capacitor+core@3.3.4/node_modules/@capacitor/haptics'
  pod 'CapacitorKeyboard', :path => '../../node_modules/.pnpm/@capacitor+keyboard@1.2.0_@capacitor+core@3.3.4/node_modules/@capacitor/keyboard'
  pod 'CapacitorLocalNotifications', :path => '../../node_modules/.pnpm/@capacitor+local-notifications@1.0.10_@capacitor+core@3.3.4/node_modules/@capacitor/local-notifications'
  pod 'CapacitorNetwork', :path => '../../node_modules/.pnpm/@capacitor+network@1.0.6_@capacitor+core@3.3.4/node_modules/@capacitor/network'
  pod 'CapacitorPushNotifications', :path => '../../node_modules/.pnpm/@capacitor+push-notifications@1.0.8_@capacitor+core@3.3.4/node_modules/@capacitor/push-notifications'
  pod 'CapacitorScreenReader', :path => '../../node_modules/.pnpm/@capacitor+screen-reader@1.0.6_@capacitor+core@3.3.4/node_modules/@capacitor/screen-reader'
  pod 'CapacitorShare', :path => '../../node_modules/.pnpm/@capacitor+share@1.1.0_@capacitor+core@3.3.4/node_modules/@capacitor/share'
  pod 'CapacitorSplashScreen', :path => '../../node_modules/.pnpm/@capacitor+splash-screen@1.2.0_@capacitor+core@3.3.4/node_modules/@capacitor/splash-screen'
  pod 'CapacitorStatusBar', :path => '../../node_modules/.pnpm/@capacitor+status-bar@1.0.6_@capacitor+core@3.3.4/node_modules/@capacitor/status-bar'
  pod 'CapacitorStorage', :path => '../../node_modules/.pnpm/@capacitor+storage@1.2.3_@capacitor+core@3.3.4/node_modules/@capacitor/storage'
  pod 'CapacitorTextZoom', :path => '../../node_modules/.pnpm/@capacitor+text-zoom@1.0.7_@capacitor+core@3.3.4/node_modules/@capacitor/text-zoom'
  pod 'CapacitorToast', :path => '../../node_modules/.pnpm/@capacitor+toast@1.0.6_@capacitor+core@3.3.4/node_modules/@capacitor/toast'
  pod 'CapacitorCrisp', :path => '../../node_modules/.pnpm/capacitor-crisp@1.0.15_@capacitor+core@3.3.4/node_modules/capacitor-crisp'
  pod 'CapacitorNativeAudio', :path => '../../node_modules/.pnpm/capacitor-native-audio@3.0.2_@capacitor+core@3.3.4/node_modules/capacitor-native-audio'
  pod 'CapacitorRateApp', :path => '../../node_modules/.pnpm/capacitor-rate-app@2.0.0_@capacitor+core@3.3.4/node_modules/capacitor-rate-app'
  pod 'CapacitorUpdater', :path => '../../node_modules/.pnpm/capacitor-updater@1.0.26_@capacitor+core@3.3.4/node_modules/capacitor-updater'
end

target 'App' do
  capacitor_pods
  # Add your Pods here
end
