name: Deploy CF Worker

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
      
jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy CF Worker
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Deploy CF Worker
        run: npx wrangler deploy ./cloudflare_workers/loadbalancer.ts
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
