name: Deploy CF Worker

on:
  workflow_dispatch:
  push:
    branches:
      - 'main2'
      
jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy CF Worker
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      
      - name: Generate cloudflare functions
        run: bun run generate:node_serverless

      - name: Generate function map
        run: bun run ./scripts/generate_cloudflare_function_map.mjs

      # - name: Install Node.js
      #   uses: actions/setup-node@v3
      #   with:
      #     node-version: 18

      - name: Deploy CF Worker
        run: bunx wrangler deploy ./cloudflare_workers/loadbalancer.ts
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
