name: Claude Assistant
on:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]
  issues:
    types: [opened, assigned, labeled]
  pull_request_review:
    types: [submitted]

permissions:
  contents: write
  pull-requests: write
  issues: write
  actions: read # Required for CI access

jobs:
  claude-response:
    runs-on: ubuntu-latest
    steps:
      - uses: anthropics/claude-code-action@beta
        with:
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          # Or use OAuth token instead:
          # claude_code_oauth_token: ${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}
          # Optional: add custom trigger phrase (default: @claude)
          # trigger_phrase: "/claude"
          # Optional: add assignee trigger for issues
          # assignee_trigger: "claude"
          # Optional: add label trigger for issues
          # label_trigger: "claude"
          # Optional: add custom environment variables (YAML format)
          # claude_env: |
          #   NODE_ENV: test
          #   DEBUG: true
          #   API_URL: https://api.example.com
          # Optional: limit the number of conversation turns
          # max_turns: "5"
          # Optional: grant additional permissions (requires corresponding GitHub token permissions)
          additional_permissions: |
            actions: read
          mcp_config: |
            {
              "mcpServers": {
                "supabase-local": {
                  "command": "bunx",
                  "args": [
                    "@modelcontextprotocol/server-postgres",
                    "postgresql://postgres:postgres@127.0.0.1:54322/postgres"
                  ]
                },
                "browser": {
                  "command": "bunx",
                  "args": [
                    "@agentdeskai/browser-tools-mcp"
                  ],
                  "env": {}
                }
              }
            }
          allowed_tools: "mcp__supabase-local,mcp__browser" # Important: Each MCP tool from your server must be listed here, comma-separated
