name: GitHub Releases to Discord

on:
  release:
    types: [published]

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  github-releases-to-discord:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: GitHub Releases to Discord
        uses: SethCohen/github-releases-to-discord@v1
        with:
            webhook_url: ${{ secrets.WEBHOOK_DISCORD_RELEASE_URL }}
            color: "2105893"
            footer_title: "Release @${{ github.repository }}"
            reduce_headings: true
