name: Send app to review

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:

permissions: {}

jobs:
  release_android:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v6
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.4'
      - name: Install Fastlane bundle
        run: bundle install
      - name: Decode Google Play Confi File
        uses: timheuer/base64-to-file@v1
        id: service_account_json_file
        with:
          fileName: serviceAccount.json
          encodedString: ${{ secrets.PLAY_CONFIG_JSON }}
      - name: Upload Android screenshots
        env:
          ANDROID_JSON_KEY_FILE: ${{ steps.service_account_json_file.outputs.filePath }}
          DEVELOPER_PACKAGE_NAME: ${{ secrets.DEVELOPER_PACKAGE_NAME }}
          FASTLANE_SKIP_UPDATE_CHECK: 'true'
        run: bundle exec fastlane android upload_screenshots
  release_ios:
    runs-on: macOS-latest
    timeout-minutes: 30
    permissions:
      contents: read
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24.x
      - uses: actions/checkout@v6
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.4'
      - name: Install Fastlane bundle
        run: bundle install
      - name: Submit iOS app for review
        env:
          GIT_USERNAME: ${{ secrets.GIT_USERNAME }}
          GIT_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          APP_STORE_CONNECT_TEAM_ID: ${{ secrets.APP_STORE_CONNECT_TEAM_ID }}
          FASTLANE_SKIP_UPDATE_CHECK: 'true'
        run: bundle exec fastlane ios submit_review
