name: Run Tests

on:
  pull_request_target:
    branches:
      - main
  merge_group:
  workflow_dispatch:
  
jobs:
  test:
    runs-on: buildjet-16vcpu-ubuntu-2204
    name: "Build code and release"
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'pnpm'
      - name: Install dependencies
        id: install_code
        run: pnpm install --frozen-lockfile
      # - name: Lint
      #   id: lint_code
      #   run: pnpm lint
        env:
          VITE_APP_URL: ${{ secrets.VITE_APP_URL }}
          VITE_VAPID_KEY: ${{ secrets.VITE_VAPID_KEY }}
          VITE_FIREBASE_CONFIG: ${{ secrets.VITE_FIREBASE_CONFIG }}
      - name: Install Supabase CLI
        uses: supabase/setup-cli@v1
        with:
          version: 1.68.6 
      - name: Run Supabase Start
        run: supabase start
      - name: Install Playwright Browsers
        run: pnpm dlx playwright install --with-deps
      - name: Run Playwright tests
        run: pnpm dlx playwright test
