name: Run Tests

on:
  pull_request_target:
    branches:
      - main
  merge_group:
  workflow_dispatch:
  
jobs:
  test:
    runs-on: ubuntu-latest	
    name: "Run Tests"
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - uses: pnpm/action-setup@v2
        name: Install pnpm
        with:
          version: 8
          run_install: false

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV
      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install

      - name: Install Supabase CLI
        uses: supabase/setup-cli@v1
        with:
          version: 1.68.6 

      - name: Run Supabase Start
        run: ENV=local supabase start -x studio,imgproxy,inbucket,logflare --ignore-health-check
      - name: Configure frontend env
        run: cp .env.exemple .env

      - name: Cache playwright binaries
        id: playwright-cache
        uses: actions/cache@v2
        with:
          path: |
            ~/Library/Caches/ms-playwright
            ~/.cache/ms-playwright
            ${{ github.workspace }}/node_modules/playwright
          key: cache-playwright-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: cache-playwright-

      - name: Install Playwright 
        shell: bash
        if: steps.playwright-cache.outputs.cache-hit != 'true'
        run: pnpm exec playwright install --with-deps chromium

      - name: Run Playwright tests
        run: pnpm exec playwright test

      - name: Upload Test Results
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: test-results
